### ISSUE TITLE
Broken site after git pull

### ISSUE THREAD

**Issue by adeleglise** [kakawait/hugo-tranquilpeak-theme#108]
### Configuration

 - **Archlinux**: 
 - **Chrome**:
 - **v0.18.1**
 - **0.2.1-ALPHA**
 - **Do you reproduce on https://tranquilpeak.kakawait.com demo?**: Nope
 

### Actual behavior
Front page is broken, have a look at https://alain.deleglise.net

### Expected behavior
Not broken :p

### Steps to reproduce the behavior

**Comment by kakawait** [comment]
Did you follow any migrations listed inside https://github.com/kakawait/hugo-tranquilpeak-theme/blob/master/CHANGELOG.md ?

**Comment by adeleglise** [comment]
Ok my bad, I was missing a f$*ùload of changes in config.toml !

**Comment by kakawait** [comment]
I tend to do no add more breaking changes. I think you should not have same experience for next release.

I had to introduce that breaking changes to improve consistency I toke that decision on earlier release. But now breaking changes will be less "breaking"

**Comment by adeleglise** [comment]
No problem, I was just assuming the role of a typical client ;)
