### ISSUE TITLE
Question - Which files and folders exactly should be copied over to the main site?

### ISSUE THREAD

**Issue by virtualjj** [kakawait/hugo-tranquilpeak-theme#109]
### Configuration

 - **Operating system with its version**: OS X El Capitan Version 10.11.6
 - **Browser with its version**: Chrome Version 55.0.2883.95 (64-bit)
 - **Hugo version**: Hugo Static Site Generator v0.18.1 BuildDate: 2016-12-30
 - **Tranquilpeak version**: 0.2.1-ALPHA
 - **Do you reproduce on https://tranquilpeak.kakawait.com demo?**: N/A
 

### Actual behavior

First thank you for this theme! Unfortunately, I am new to Hugo so please bear with me. Also, I understand that my version of Hugo - v0.18.1 is above the listed capability version of v0.17 but I think my question is unrelated - apologies if that is not the case.

I have successfully installed the the theme and gotten the full site to work locally but...by haphazardly copying files; I'm not understanding which files need to be manually copied over to the main site.

Here is what I did in order:

![image](https://cloud.githubusercontent.com/assets/10323889/22087898/feb0bb78-de23-11e6-8d0f-ee0a15107e74.png)

I made the configuration change per the **Language configuration** step:

![image](https://cloud.githubusercontent.com/assets/10323889/22087913/1de3dffc-de24-11e6-925e-551ebf6711a3.png)

Then build the site:

![image](https://cloud.githubusercontent.com/assets/10323889/22088052/d16330be-de24-11e6-9f7f-3912a842fa3f.png)

And then view it:

![image](https://cloud.githubusercontent.com/assets/10323889/22088090/0824cf54-de25-11e6-8bfc-a28fa6b6caa8.png)

The complete site doesn't render:

![image](https://cloud.githubusercontent.com/assets/10323889/22088112/2d404282-de25-11e6-9381-453be585ed35.png)

But then the **Theme configuration** step says to copy over the example configuration - this will overwrite **Language configuration** step. Okay, so I tried that:

![image](https://cloud.githubusercontent.com/assets/10323889/22088208/b7ccb444-de25-11e6-9642-a8c247b25042.png)

And now get this:

![image](https://cloud.githubusercontent.com/assets/10323889/22088219/ce3d0c74-de25-11e6-844e-be035ff75fbc.png)

Fix the **No 'baseURL' set in configuration or as a flag.** message and try again:

![image](https://cloud.githubusercontent.com/assets/10323889/22088256/202ece3c-de26-11e6-85bf-f8831a8fbce2.png)

Same result:

![image](https://cloud.githubusercontent.com/assets/10323889/22088260/2717a7e6-de26-11e6-9ec4-dc6a7593fbdd.png)

At this point, this is what my directory structure looks like:

```
Tranquilpeak Tester: tree -a
.
|-- .DS_Store
|-- archetypes
|-- config.toml
|-- content
|-- data
|-- layouts
|-- public
|   |-- .DS_Store
|   |-- 404.html
|   |-- css
|   |   `-- style-gwlo24d2hxipxk8bi1sxik0zhlpn9t7ebcmgp9kubmmcjfzlavuyhvbqumhn.min.css
|   |-- images
|   |   |-- cover-v1.2.0.jpg
|   |   `-- cover.jpg
|   |-- index.html
|   |-- index.xml
|   |-- js
|   |   `-- script-wl33z0n6ocaypepiqrazthtivfrliqijej4rq8ek8gvrv1awftmgjuv8k4zc.min.js
|   |-- page
|   |   |-- .DS_Store
|   |   `-- 1
|   |       `-- index.html
|   `-- sitemap.xml
|-- static
`-- themes
    |-- .DS_Store
    `-- hugo-tranquilpeak-theme
        |-- .DS_Store
        |-- .eslintignore
        |-- .eslintrc
        |-- .git
        |   |-- HEAD
        |   |-- config
        |   |-- description
        |   |-- hooks
        |   |   |-- applypatch-msg.sample
        |   |   |-- commit-msg.sample
        |   |   |-- post-update.sample
        |   |   |-- pre-applypatch.sample
        |   |   |-- pre-commit.sample
        |   |   |-- pre-push.sample
        |   |   |-- pre-rebase.sample
        |   |   |-- pre-receive.sample
        |   |   |-- prepare-commit-msg.sample
        |   |   `-- update.sample
        |   |-- index
        |   |-- info
        |   |   `-- exclude
        |   |-- logs
        |   |   |-- HEAD
        |   |   `-- refs
        |   |       |-- heads
        |   |       |   `-- master
        |   |       `-- remotes
        |   |           `-- origin
        |   |               `-- HEAD
        |   |-- objects
        |   |   |-- info
        |   |   `-- pack
        |   |       |-- pack-693fc978d72eb564d72711e22b33cf56ae12f077.idx
        |   |       `-- pack-693fc978d72eb564d72711e22b33cf56ae12f077.pack
        |   |-- packed-refs
        |   `-- refs
        |       |-- heads
        |       |   `-- master
        |       |-- remotes
        |       |   `-- origin
        |       |       `-- HEAD
        |       `-- tags
        |-- .github
        |   |-- CONTRIBUTING.md
        |   `-- ISSUE_TEMPLATE.md
        |-- .gitignore
        |-- CHANGELOG.md
        |-- Gruntfile.js
        |-- LICENSE
        |-- README.md
        |-- archetypes
        |   `-- post.md
        |-- docs
        |   |-- developer.md
        |   |-- img
        |   |   |-- with_hierarchical_categories.png
        |   |   `-- without_hierarchical_categories.png
        |   `-- user.md
        |-- exampleSite
        |   |-- .gitignore
        |   |-- config.toml
        |   |-- content
        |   |   `-- post
        |   |       |-- Cover-image-showcase.md
        |   |       |-- Elements-showcase.md
        |   |       |-- Hidden-pagination-showcase.md
        |   |       |-- Hidden-social-section-showcase.md
        |   |       |-- Hidden-tag-section-showcase.md
        |   |       |-- Image-gallery-showcase.md
        |   |       |-- Tags-plugins-showcase.md
        |   |       |-- Video-integrations-showcase.md
        |   |       |-- Welcome-to-the-new-Tranquilpeak.md
        |   |       |-- highlighted-code-showcase.md
        |   |       |-- \344\270\255\346\226\207\346\270\254\350\251\246.md
        |   |       `-- \346\227\245\346\234\254\350\252\236\343\203\206\343\202\271\343\203\210.md
        |   `-- static
        |       `-- img
        |           `-- showcase.png
        |-- i18n
        |   |-- de-de.yaml
        |   |-- en-us.yaml
        |   |-- es-es.yaml
        |   |-- fr-fr.yaml
        |   |-- ja.yaml
        |   |-- pt-br.yaml
        |   |-- ru.yaml
        |   |-- vi.yaml
        |   |-- zh-cn.yaml
        |   `-- zh-tw.yaml
        |-- images
        |   |-- screenshot.png
        |   `-- tn.png
        |-- layouts
        |   |-- 404.html
        |   |-- _default
        |   |   |-- list.html
        |   |   |-- single.html
        |   |   `-- summary.html
        |   |-- index.html
        |   |-- partials
        |   |   |-- about.html
        |   |   |-- archive-post.html
        |   |   |-- cover.html
        |   |   |-- foot.html
        |   |   |-- foot_end.html
        |   |   |-- foot_start.html
        |   |   |-- footer.html
        |   |   |-- head.html
        |   |   |-- head_end.html
        |   |   |-- head_start.html
        |   |   |-- header.html
        |   |   |-- internal
        |   |   |   |-- date.html
        |   |   |   |-- recursive-categories-1.html
        |   |   |   |-- recursive-categories-2.html
        |   |   |   |-- recursive-categories-full-1.html
        |   |   |   `-- recursive-categories-full-2.html
        |   |   |-- menu.html
        |   |   |-- pagination.html
        |   |   |-- post
        |   |   |   |-- actions.html
        |   |   |   |-- category.html
        |   |   |   |-- disqus.html
        |   |   |   |-- gallery.html
        |   |   |   |-- header-cover.html
        |   |   |   |-- header.html
        |   |   |   |-- meta.html
        |   |   |   |-- share-options.html
        |   |   |   `-- tag.html
        |   |   |-- script.html
        |   |   |-- search.html
        |   |   `-- sidebar.html
        |   |-- shortcodes
        |   |   |-- alert.html
        |   |   |-- blockquote.html
        |   |   |-- codeblock.html
        |   |   |-- hl-text.html
        |   |   |-- image.html
        |   |   |-- jsfiddle.html
        |   |   |-- pullquote.html
        |   |   |-- tabbed-codeblock.html
        |   |   `-- wide-image.html
        |   `-- taxonomy
        |       |-- archive.terms.html
        |       |-- category.html
        |       |-- category.terms.html
        |       |-- tag.html
        |       `-- tag.terms.html
        |-- package.json
        |-- showcase.png
        |-- src
        |   |-- images
        |   |   |-- cover-v1.2.0.jpg
        |   |   `-- cover.jpg
        |   |-- js
        |   |   |-- .eslintrc.json
        |   |   |-- about.js
        |   |   |-- archives-filter.js
        |   |   |-- categories-filter.js
        |   |   |-- codeblock-resizer.js
        |   |   |-- fancybox.js
        |   |   |-- header.js
        |   |   |-- image-gallery.js
        |   |   |-- post-bottom-bar.js
        |   |   |-- search-modal.js
        |   |   |-- share-options.js
        |   |   |-- sidebar.js
        |   |   |-- smartresize.js
        |   |   |-- tabbed-codeblocks.js
        |   |   `-- tags-filter.js
        |   `-- scss
        |       |-- base
        |       |   |-- _base.scss
        |       |   `-- _custom.scss
        |       |-- components
        |       |   |-- _alert.scss
        |       |   |-- _archive.scss
        |       |   |-- _box.scss
        |       |   |-- _button.scss
        |       |   |-- _caption.scss
        |       |   |-- _code.scss
        |       |   |-- _figure.scss
        |       |   |-- _form.scss
        |       |   |-- _hide.scss
        |       |   |-- _highlight-text.scss
        |       |   |-- _icon.scss
        |       |   |-- _image-gallery.scss
        |       |   |-- _link.scss
        |       |   |-- _main-content.scss
        |       |   |-- _markdown.scss
        |       |   |-- _media.scss
        |       |   |-- _modal.scss
        |       |   |-- _pagination.scss
        |       |   |-- _post-actions.scss
        |       |   |-- _post-header-cover.scss
        |       |   |-- _post.scss
        |       |   |-- _postShorten.scss
        |       |   |-- _pullquote.scss
        |       |   |-- _share-options-bar.scss
        |       |   |-- _tag.scss
        |       |   |-- _text.scss
        |       |   |-- _tooltip.scss
        |       |   `-- _video.scss
        |       |-- layouts
        |       |   |-- _about.scss
        |       |   |-- _blog.scss
        |       |   |-- _bottom-bar.scss
        |       |   |-- _cover.scss
        |       |   |-- _footer.scss
        |       |   |-- _header.scss
        |       |   |-- _main.scss
        |       |   `-- _sidebar.scss
        |       |-- pages
        |       |   `-- _search.scss
        |       |-- themes
        |       |   |-- _hljs-custom.scss
        |       |   `-- _hljs-tranquilpeak.scss
        |       |-- tranquilpeak.scss
        |       `-- utils
        |           |-- _fonts.scss
        |           |-- _variables.scss
        |           `-- mixins
        |               |-- _bottom-bar.scss
        |               |-- _button.scss
        |               |-- _category.scss
        |               |-- _form.scss
        |               |-- _header.scss
        |               |-- _main.scss
        |               |-- _opacity.scss
        |               |-- _post-header-cover.scss
        |               |-- _prefix.scss
        |               |-- _share-options-bar.scss
        |               |-- _sidebar.scss
        |               `-- _tag.scss
        |-- static
        |   |-- css
        |   |   `-- style-gwlo24d2hxipxk8bi1sxik0zhlpn9t7ebcmgp9kubmmcjfzlavuyhvbqumhn.min.css
        |   |-- images
        |   |   |-- cover-v1.2.0.jpg
        |   |   `-- cover.jpg
        |   `-- js
        |       `-- script-wl33z0n6ocaypepiqrazthtivfrliqijej4rq8ek8gvrv1awftmgjuv8k4zc.min.js
        |-- tasks
        |   |-- config
        |   |   |-- clean.js
        |   |   |-- concat.js
        |   |   |-- cssmin.js
        |   |   |-- exec.js
        |   |   |-- replace.js
        |   |   |-- sails-linker.js
        |   |   |-- sass.js
        |   |   |-- sync.js
        |   |   |-- uglify.js
        |   |   `-- watch.js
        |   |-- pipeline.js
        |   `-- register
        |       |-- build.js
        |       |-- buildProd.js
        |       |-- compileAssets.js
        |       |-- default.js
        |       |-- eslint.js
        |       |-- linkAssets.js
        |       |-- linkAssetsProd.js
        |       `-- syncAssets.js
        `-- theme.toml

65 directories, 227 files
```

I will start by copying **themes/hugo-tranquilpeak-theme/layouts/** over to .

![image](https://cloud.githubusercontent.com/assets/10323889/22088949/171b1c06-de2b-11e6-9f91-b7a6a95e97f1.png)

No change:

![image](https://cloud.githubusercontent.com/assets/10323889/22088962/2d24cdf8-de2b-11e6-8e88-b782faba87ce.png)

Next I copied the contents of static:

![image](https://cloud.githubusercontent.com/assets/10323889/22089017/ab011c90-de2b-11e6-8826-4eba5a7a9cdf.png)

No change.

Next I copied the contents of src:

![image](https://cloud.githubusercontent.com/assets/10323889/22089331/bb4cf7f2-de2d-11e6-9372-75654c01ef29.png)

No change.

Anyway, I've kept doing these iterations of copying over files and no luck so I ended up doing this instead:

1. Start over with a new site
2. Change directory into the new site themes directory
3. Clone Tranquilpeak
4. Change back to the main site directory
5. Copy the contents of exampleSite to the main site directory
6. Copy ALL files under hugo-tranquilpeak-theme into the main site directory
7. Remove the exampleSite directory from the main site directory
8. Build the site

![image](https://cloud.githubusercontent.com/assets/10323889/22089701/4ed713de-de30-11e6-9e04-c4dce8d69046.png)

9. Modify conf.toml and add the base URL. (probably should have done this before step 8)
10. Start the local Hugo server using the Tranquipeak theme
11. Use the URL to view the site

![image](https://cloud.githubusercontent.com/assets/10323889/22089800/df31ac3c-de30-11e6-890b-582ff5e478c6.png)

Full site has now rendered:

![image](https://cloud.githubusercontent.com/assets/10323889/22089825/07834736-de31-11e6-9caf-5e4d0be13ba7.png)

So, although I got the site to load and render, I'd like to know which files exactly are required to be copied to the main site. Thanks in advance!

**Comment by kakawait** [comment]
@virtualjj detailed issue 👍 Thank.

To respond to 

> I'd like to know which files exactly are required to be copied to the main site

1. Clone/Copy/Download (whatever) theme on `themes/` (I advice to name your folder `hugo-tranquilpeak-theme` after cloning/copying/downloading)
2. Copy `exampleSite/config.toml` to your hugo blog root folder
3. Edit `config.toml` (changing default value, avatar, name, url, etc).

If you did that you should have (I take your screenshot)

![](https://cloud.githubusercontent.com/assets/10323889/22088219/ce3d0c74-de25-11e6-844e-be035ff75fbc.png)

However you can complain that there is nothing on sidebar.

**In fact** you need at least 1 page/post to see sidebar render, so you can create a new post using `hugo` command tool (see doc https://gohugo.io/overview/quickstart/#step-3-add-content) 

```
hugo new post/welcome.md
```

Then you should see

![welcome_tranquilpeak](https://cloud.githubusercontent.com/assets/275609/22181289/b8376ba2-e089-11e6-9aaf-79728fee8b74.png)

I don't really recommand you to copy `exampleSite/content` folder because it contains content that illustrate theme feature, that is not the goal of your blog :)

Else you don't need anything.

To conclude the only thing you have to copy from theme folder to your hugo folder is `exampleSite/config.toml` (and please adapt it for your needs)

**Comment by virtualjj** [comment]
Agghh! Okay, got it. Thank  you for the information - looks like I was thinking about this too hard. Still much to learn! Thank you again!

**Comment by kakawait** [comment]
Even me I didn't know about the "bug" when loading theme without any page/post. I will check if I can fix it but not first priority
