### ISSUE TITLE
Archives Link 404s on Hugo 0.18.1

### ISSUE THREAD

**Issue by stantonc** [kakawait/hugo-tranquilpeak-theme#111]
### Configuration

 - **Operating system with its version**: OS X 10.12.2
 - **Browser with its version**: Chrome 55.0.2883.95
 - **Hugo version**: 0.18.1
 - **Tranquilpeak version**: 0.2.1-ALPHA
 - **Do you reproduce on https://tranquilpeak.kakawait.com demo?**: No, but I can reproduce using the exampleSite content
 
### Actual behavior
Hugo 0.18.1 does not create any content for the archives/ link off of the sidebar. Instead, opening the link produces "404 page not found". Downgrading to Hugo 0.17 fixes the issue, so something must have changed between the two versions.

### Expected behavior
When I open the Archives link in Hugo 0.18.1, I expect the Archives page to appear like it does in 0.17.

### Steps to reproduce the behavior
1. Create a Hugo test site and populate with content, or use the exampleSite content.
2. Copy the theme's exampleSite/config.toml to the site root.
3. Start Hugo 0.18.1 using "hugo server"
4. Browse to localhost:1313
5. Click on Archives

**Comment by kakawait** [comment]
Thank you for reporting. I have the same bug I will check that.

**Comment by kakawait** [comment]
I opened an issue on hugo directly, let see what they will answer https://github.com/spf13/hugo/issues/2977

**Comment by kakawait** [comment]
For instance I can only recommand you to rollback to `0.17` until I found a solution or Hugo fix it directly

**Comment by kakawait** [comment]
@stantonc issue was fixed on Hugo https://github.com/spf13/hugo/issues/2977 please upgrade to `0.20` when released or keep `0.17`

**Comment by kakawait** [comment]
I will close the issue when `0.20` will be released

**Comment by stantonc** [comment]
Thanks for chasing this down. I'll keep an eye out for 0.20.

**Comment by martinhoefling** [comment]
@kakawait: ist this really fixed in hugo 0.20? I've built hugo master from source (18f5f3c14c50ad69e8956070b52f31d9331b1de7) but still have the issue that archive index file is not created.

**Comment by kakawait** [comment]
It should be I do not try by myself. I will check

**Comment by kakawait** [comment]
@martinhoefling Hugo `0.20` just released (if you're using _homebrew_ simply `brew update && brew upgrade hugo`).

I tried with `Hugo Static Site Generator v0.20 darwin/amd64 BuildDate: 2017-04-10T15:04:57+02:00`, archive links work like a charm.

Could you confirm please and if not working can you print you `hugo version` and gimme your theme release version?

**Comment by kakawait** [comment]
Please re-open if is not working
