### ISSUE TITLE
Doc Typo: Appending <!-- more --> to a text to make it the excerpt of a post does not work

### ISSUE THREAD

**Issue by ebouchut** [kakawait/hugo-tranquilpeak-theme#113]
The documentation mentions that using `<!-- more -->`  delimits the end of a post excerpt.
However, it does not work as is.
Please do note **there is a space** in between `more` and the beginning (`<!--`) and the end (`-->`) HTML comment tag.

### Configuration

 - **Operating system with its version**:  `10.12.3`
 - **Browser with its version**:  `Firefox 51.0.1`
 - **Hugo version**: `v0.18.1 BuildDate: 2016-12-29T18:12:41+01:00`
 - **Tranquilpeak version**:  `0.2.1-ALPHA`
 - **Do you reproduce on https://tranquilpeak.kakawait.com demo?**:  
 
### Steps to reproduce the behavior

Create a new post with the following
```markdown
Once this is fixed,
<!-- more -->
You should not see the content of this post in the excerpt.
```

### Actual behavior

The whole article is displayed instead of only the post excerpt.
```
Once this is fixed,
You should not see the content of this post in the excerpt.
Continue reading...
```

### Expected behavior

Only the text marked as a post excerpt should be displayed as such.
```
Once this is fixed,
Continue reading...
```

**Comment by kakawait** [comment]
@ebouchut thank for reporting, you are talking about *spaces* between `more`, do you mean it works without *spaces*?

If yes it will be easy to fix, just about regexp-ing :)

Else I will check that

**Comment by ebouchut** [comment]
The workaround I found out so far is to use `<!--more-->`  with `more` not surrounded with space.
How about updating the doc to reflect this?

**Comment by kakawait** [comment]
Ho yes `<!--more-->` is not handle by theme but is `Hugo` feature (https://gohugo.io/content/summaries/) unlike `<!--toc-->`.

So yes I can't do anything except update documentation.

Good catch

**Comment by ebouchut** [comment]
It seems to me, Hugo only handles `<!--more-->` 
Source: https://gohugo.io/content/summaries/

**Comment by kakawait** [comment]
@ebouchut Yes but I was thinking that `<!--more-->` isn't a built-in `Hugo` feature but an addition from the theme like `<!--toc-->`, I was wrong

**Comment by ebouchut** [comment]
Yes thank you for the quick feedback.
I just noticed that also, this why our replies stepped on each other toes ;-).

I suggest we stick with what is available in Hugo and update the doc to reflect this, because this is a minor typo in fact.

**Comment by ebouchut** [comment]
@kakawait,  PR #114  contains fixes the user's documentation and the post archetype.
It is based on develop.
Let me know what you think about it.

**Comment by ebouchut** [comment]
Thanks.
I can't wait for [Sunday](/kakawait/hugo-tranquilpeak-theme/milestone/11) 😉 .

**Comment by kakawait** [comment]
@ebouchut yes sorry I delayed new version due to bug on `Hugo 0.18` but I think I will release it and try to fix it on next version

**Comment by ebouchut** [comment]
I was just kidding, no worries at all.
