### ISSUE TITLE
Can't get gravatar rendered on Hugo 0.18.1

### ISSUE THREAD

**Issue by masknu** [kakawait/hugo-tranquilpeak-theme#117]
### Configuration

 - **Ubuntu 16.04 LTS**: 
 - **Chromium 55.0.2883.87**:
 - **Hugo 0.18.1**: 
 - **Tranquilpeak 0.2.2-ALPHA**: 
 - **Didn't reproduce on https://tranquilpeak.kakawait.com demo?**:
 

### Behaviour
Gravatar on sidebar can't get rendered.

### Expectation
Gravatar should show up.

### Reproduce
Copy the `config.toml` from hugo-tranquilpeak-theme/exampleSite to Site root.
At site root directory, generate the site by `hugo server -wDs . -d dev`.

It might be related to [Breaking API-change re Author](https://github.com/spf13/hugo/issues/2464).

**Comment by kakawait** [comment]
Thank for reporting. I will check the issue you linked.

But could you please try with `gravataremail` (lowercase) key ?

**Comment by masknu** [comment]
I tried `gravataremail`. It still behaved the same way.

**Comment by kakawait** [comment]
I did have an issue with `gravatarEmail` when releasing `2.2.0-ALPHA` but it seems to not be enough https://github.com/kakawait/hugo-tranquilpeak-theme/commit/01447633fba1e5c1ef342b0b8be5b5f7a3e8fdd7

**Comment by kakawait** [comment]
@masknu I tried myself using `master` branch but I don't not reproduce. Do you have a way to print me your commit version of theme?

**Comment by kakawait** [comment]
@masknu or blog repository to be able to test by myself

**Comment by masknu** [comment]
@kakawait  I'm confused. After I updated Hugo to **v0.2-DEV** version, the gravatar could be displayed. All things are normal now.

**Comment by kakawait** [comment]
@masknu I was speaking about `tranquilpeak` theme version not `Hugo` but if hugo fix it and it's ok for you no prob.
