### ISSUE TITLE
Automatic navigation to tags

### ISSUE THREAD

**Issue by yamila-moreno** [kakawait/hugo-tranquilpeak-theme#119]
Hi! I have a question about automatic links in the posts. Again (as in https://github.com/kakawait/hugo-tranquilpeak-theme/issues/118) I don't see this behaviour in other hugo blogs so I assume is part of tranquilpeak theme; I hope I'm right.

What happens now is that in the first post I can navigate:
- on one hand to the newer post
- on the other hand to the first "tag/" page in alphabetic order (AFAIK), which is unexpected and undesired.

My question is: is there any way to avoid this behaviour? 
Thanks for your time! :D

**Comment by kakawait** [comment]
I'm not totally sure to understand well your problem. So sorry in advance if I'm out of subject. Do you mean you want to remove tags buttons/links at end of each blog post?

**Comment by yamila-moreno** [comment]
Hi! Let me try with this screenshot (attached). It's a screenshot of the first post, and it has "previous" and "next" buttons active (I would expect that only one is active).

- one of the buttons goes to the newer post
- the other button goes to the "tags/" URL instead of the `🚫` signal. 

In your theme demo, this behaviour doesn't happen; if you go to the first post (https://tranquilpeak.kakawait.com/2013/01/japanese-test/) you can check that one of the buttons is disabled.

I hope it's more clear now :) 

![hugo](https://cloud.githubusercontent.com/assets/3340793/23344148/95d7dd80-fc77-11e6-92b7-82c14359f56e.png)

**Comment by kakawait** [comment]
Hum that strange and unexpected behavior I will try to check that

**Comment by yamila-moreno** [comment]
Thanks!

**Comment by kakawait** [comment]
Confirmed is bug using `Hugo v0.18`

Temporary fix is to rollback to `Hugo v0.17`.

There are many bug since `Hugo v0.18` is really not a good version :'(

**Comment by yamila-moreno** [comment]
Hi! I just tested this bug using the new release (0.19) and the bug is still there. I'll check hugo issues and if it wasn't noticed, I'll create a new one. 

With 0.17 release it works fine!

**Comment by kakawait** [comment]
In fact since 0.18 everything becomes a `Page` that the main reason of that behavior http://bepsays.com/en/2016/12/19/hugo-018/
