### ISSUE TITLE
favicon not supported

### ISSUE THREAD

**Issue by mehdy** [kakawait/hugo-tranquilpeak-theme#126]
[here in docs](https://github.com/kakawait/hugo-tranquilpeak-theme/blob/master/docs/user.md#customization) says that I can customize my `favicon` but [here in the code](https://github.com/kakawait/hugo-tranquilpeak-theme/blob/master/layouts/partials/head.html#L35) it's hard-coded to `/favicon.png`

**Comment by kakawait** [comment]
@mehdy nice catch I will fix it up asap
