### ISSUE TITLE
the case-sensitive problem 

### ISSUE THREAD

**Issue by mehdy** [kakawait/hugo-tranquilpeak-theme#127]
I was struggling the `thumbnailImagePosition` whe it wasn't working. I traced the code and found out that it's because in [here](https://github.com/kakawait/hugo-tranquilpeak-theme/blob/master/layouts/_default/summary.html) it has some case-sensitive matching problem. (although in the docs it says `thumbnailImagePosition` but the code looks for `thumbnailimageposition`. the sad point is that I skimmed the code and the problem isn't limited to this option. I think the whole code base needs a refactoring.

**Comment by mehdy** [comment]
sorry about the mislead! I read the code carefully and I figured out the problem is that the code doesn't look for the global `thumbnailImagePosition`. It just read from each post configuration

**Comment by kakawait** [comment]
Ha yes every settings are not necessarily duplicated between per post and global. For your use case you can use archetype to set default per post setting

**Comment by kakawait** [comment]
I will close the issue please re-open if something is not ok for you
