### ISSUE TITLE
Current TTF font files contain only latin characters

### ISSUE THREAD

**Issue by DeziderMesko** [kakawait/hugo-tranquilpeak-theme#129]
### Configuration

 - **Operating system with its version**: 10.12.3
 - **Browser with its version**: Chrome 56
 - **Hugo version**: 0.19
 - **Tranquilpeak version**: 0.2.2-alpha
 - **Do you reproduce on https://tranquilpeak.kakawait.com demo?**: yes
 

### Actual behavior
Characters with accent (ěščřžýáí) are replaced with fallback font, even Merriweather is supporting these characters. 

### Expected behavior
Characters are rendered with Merriweather font

### Steps to reproduce the behavior
Just use chrome dev tools to insert characters above to demo site.

Issue is caused by using TTF files which don't have these characters available. I've tried latest version of the font (v15) and issue still persist.
You can solve this by replacing _fonts.scss content with:
https://fonts.googleapis.com/css?family=Merriweather:300,300i,400,400i,700,700i%7COpen+Sans:400,700

**Comment by kakawait** [comment]
@DeziderMesko May I miss something but when I tried myself (on https://tranquilpeak.kakawait.com) using chrome I have following result

![screen shot 2017-03-31 at 13 48 02](https://cloud.githubusercontent.com/assets/275609/24549262/c9ef773a-1618-11e7-8e5c-f22f06272c68.png)

Font seems to be correctly `Merriweather`

**Comment by DeziderMesko** [comment]
Hi, sorry for late reply, missed the notification.

I'm font noob as well. :-) Please notice that your first 5 letters have different size than last three. Font statically referenced in _fonts.scss is imho pure latin version. While generic query returns font version based on browser abilities (ttf, woff2 etc) and accent requirements.

BTW: maybe I'm wrong, but in case that you have font installed in MacOS this is used by chrome instead of the referenced one. So even if css refers to right font file, if you have installed just latin font locally, it will be used.

<img width="823" alt="screen shot 2017-04-06 at 11 45 47" src="https://cloud.githubusercontent.com/assets/4199212/24748039/b68000e8-1abe-11e7-9187-2ff2c0be4439.png">
