### ISSUE TITLE
customCSS not working

### ISSUE THREAD

**Issue by huynle** [kakawait/hugo-tranquilpeak-theme#137]
Hi,

I am a complete newbie to this issue reporting on github (my first one actually). This is my first Hugo/Golang/CSS/HTML related project that i've been digging into. I'm trying to set my css for different elements on my post, and cannot do it for the life of me. I've checked around and see that the customCSS is loaded in the `partial/head.html`. Besides that, I'm not completely sure what else I can do to check/debug.

I really appreciate the work that you guys put into this beautiful theme, it's been a pleasure poking around and seeing the work that went into this!

Thanks,
Huy

### Configuration
 - Ubuntu 16.04
 - chome Version 55.0.2883.87 (64-bit)
 - Hugo Static Site Generator v0.20-DEV linux/amd64 BuildDate: 2017-03-04T15:58:45-08:00
 - "version": "0.2.3-ALPHA",
 

### Actual behavior
custom css element cannot be generated in post.. 

### Expected behavior
expecting css to be applied to elements on mypost.md

### Steps to reproduce the behavior
- custom css is placed in `static/css/custom.css`
- in `config.toml` the parameter `customCSS = ["css/custom.css"]`
- in a mypost.md, i have the following string  `<bioelement>Using CSS element</bioelement>`
- although `bioelement` is defined in custom.css, the i cannot see the result

**Comment by kakawait** [comment]
@huynle did you correctly put `customCSS = ["css/custom.css"]` inside `[params]` section on `config.toml` like following:

```toml
[params]
  customCSS = ["css/custom.css"]
```

and not directly on _root_ level?

**Comment by huynle** [comment]
@kakawait I believe I had it in the correct place, attached below is an image of my config.toml for the customCSS. There I did double checked that it is under `[params]`. 

![image](https://cloud.githubusercontent.com/assets/2416122/24871728/78a474a2-1dcf-11e7-90ce-143b3a6efe1d.png)

Additionally, my css is under my `blog/static/css/custom.css` where blog is my main Hugo folder.

**Comment by kakawait** [comment]
@huynle but if you look at your html source using Chrome for example and _view page source_, could you please add your whole `<head></head>` section?

**Comment by huynle** [comment]
@kakawait, attached is my `<head>` section youre asking for. I can see that youre theme stylesheet in there, but the custom one is not loaded.

``` html
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="generator" content="Hugo 0.21-DEV">
    <title>Life:Learn</title>
    <meta name="author" content="Huy Le">
    <meta name="keywords" content="">

    <link rel="icon" href="http://localhost:1313/favicon.png">
    
      <link rel="alternate" type="application/rss+xml" title="RSS" href="http://localhost:1313/index.xml">

    <meta name="description" content="Brain dumping!">
    <meta property="og:description" content="Brain dumping!">
    <meta property="og:type" content="blog">
    <meta property="og:title" content="Life:Learn">
    <meta property="og:url" content="/">
    <meta property="og:site_name" content="Life:Learn">
    <meta name="twitter:card" content="summary">
    <meta name="twitter:title" content="Life:Learn">
    <meta name="twitter:description" content="Brain dumping!">
    
      <meta name="twitter:creator" content="@huynle">

      <meta property="og:image" content="//www.gravatar.com/avatar/04e1ce651ee5ca14d4c25e7dce0a42cc?s=640">

    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.4/jquery.fancybox.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.4/helpers/jquery.fancybox-thumbs.min.css">

    <link rel="stylesheet" href="http://localhost:1313/css/style-gwlo24d2hxipxk8bi1sxik0zhlpn9t7ebcmgp9kubmmcjfzlavuyhvbqumhn.min.css">
    
  </head>
```

**Comment by huynle** [comment]
I don't want to fill this issue with codes, but this is the exact line I'm copying from the package.json in the theme folder.
```js
  "version": "0.2.3-ALPHA",
```
as for my config file, it is in the directory of `blog/config.toml`.

I'm attaching a slimmed down version of my blog for you to debug, thanks for looking into this. I'm sure it could be a very small mistake from my side!
[blog_upload.zip](https://github.com/kakawait/hugo-tranquilpeak-theme/files/914077/blog_upload.zip)

**Comment by kakawait** [comment]
@huynle the issue is on `config.toml` you put your `customCSS` and `customJS` not after `[params.header.rightLink]` because you will not be anymore on `[params]` section

Simply put

```toml
# Custom CSS. Put here your custom CSS files. They are loaded after the theme CSS;
# they have to be referred from static root. Example
customCSS = ["css/custom.css"]

# Custom JS. Put here your custom JS files. They are loaded after the theme JS;
# they have to be referred from static root. Example
customJS = ["js/custom.js"]
```

between `[params]` and `[params.header.rightLink]`

**Comment by huynle** [comment]
I uncommented it from the original `config.toml` file that came with the sample site. And verified it had two spaces before the `customCSS` and `customJS` in the config file, so i thought it was still under `[params]`. 

 I moved these to values to the top right under `[params]` and now it's working!

Thank you for taking the time to help me out!

**Comment by kakawait** [comment]
> I uncommented it from the original config.toml

You're write is error, I will fix it that why I will re-open issue.
