### ISSUE TITLE
Introduce Fetch Injection?

### ISSUE THREAD

**Issue by jhabdas** [kakawait/hugo-tranquilpeak-theme#139]
This is a lovely theme, @kakawait. I noticed there are a few blocking CSS requests in the `head.html` partial for loading non-critical CSS. Thoughts on loading those asynchronously using [Fetch Inject](https://www.npmjs.com/package/fetch-inject) to speed up the page load a little?

**Comment by kakawait** [comment]
@jhabdas I will checkout that lib, but I'm not 100% fan of using `JS` to load resources. Other way is maybe to use `HTML5` feature like `async` or `deferred`

**Comment by jhabdas** [comment]
I feel you about loading with JS. And I'm not a fan of the argument <q>everyone uses JS</q>, because they don't. Depending on your browser support requirements, since `link` doesn't support `async` attribute and will cause a blocking request, an alternative would be to look into `preload` alongside [server push](https://www.smashingmagazine.com/2017/04/guide-http2-server-push/) over HTTP/2.

As for loading JS with JS using `async`, that makes sense and you can kick off all requests `async` in the head of the document without causing race conditions. More info here:

https://github.com/jhabdas/fetch-inject#managing-asynchronous-dependencies

Wanted to bring it to your attention in case you were doing any perf optimizations. Thanks for your consideration. Will be watching your theme. It's stacked! 😄
