### ISSUE TITLE
Add theme version on meta as same as hugo version

### ISSUE THREAD

**Issue by kakawait** [kakawait/hugo-tranquilpeak-theme#140]
as same as 

```html
<meta name="generator" content="Hugo 0.19">
```

I think it can be a good option to add also theme version like 

```html
<meta name="theme" content="Tranquilpeak 0.3.1-BETA">
```

**Comment by jhabdas** [comment]
That's actually not a valid meta tag. http://devdocs.io/html/element/meta

**Comment by jhabdas** [comment]
I _think_ what you want to do is override the _generator_ meta tag with additional information.

**Comment by kakawait** [comment]
Nice catch. I didn't know there was a list of meta

**Comment by jhabdas** [comment]
No problemo. Devdocs is open source, offline capable and pulls data from trusted sources like MDN. Use it like it's going out of style.
