### ISSUE TITLE
Inconsistent font size, when combined English with Russian language.

### ISSUE THREAD

**Issue by vbauerster** [kakawait/hugo-tranquilpeak-theme#142]
### Configuration

 - **Operating system with its version**: 
macOS Sierra 10.12.4
 - **Browser with its version**:
Chrome Version 57.0.2987.133 (64-bit)
 - **Hugo version**: 
v0.20
 - **Tranquilpeak version**: 
0.3.0-BETA
 

### Actual behavior
[![En-Ru-font-size.png](https://s25.postimg.org/oecjw1az3/En-_Ru-font-size.png)](https://postimg.org/image/7129h6fnv/)

Full sample page is [here](https://vbauerster.github.io/2017/04/%D0%B1%D0%B5%D0%B7%D0%B1%D0%BE%D0%BB%D0%B5%D0%B7%D0%BD%D0%B5%D0%BD%D0%BD%D0%BE%D0%B5-%D1%80%D0%B0%D0%B7%D1%80%D0%B5%D1%88%D0%B5%D0%BD%D0%B8%D0%B5-merge-%D0%BA%D0%BE%D0%BD%D1%84%D0%BB%D0%B8%D0%BA%D1%82%D0%BE%D0%B2-%D0%B2-git/).
### Expected behavior
Well it is obvious that English font is a bit larger when combined with Russian(Cyrillic) font.
Expected font sizes to be the same.

I've tried changing both `languageCode` and `defaultContentLanguage` to "ru", but it didn't help.

**Comment by kakawait** [comment]
Yes problem is related directly to the font itself. I will fix it https://github.com/kakawait/hugo-tranquilpeak-theme/issues/129

**Comment by vbauerster** [comment]
Thank you for such quick fix!
