### ISSUE TITLE
Server side code block goes outside highlight block

### ISSUE THREAD

**Issue by deimosfr** [kakawait/hugo-tranquilpeak-theme#148]
### Configuration

 - **Operating system with its version**: Arch Linux x64
 - **Browser with its version**: Google Chrome Version 57.0.2987.133 (64-bit)
 - **Hugo version**: v0.20.1
 - **Tranquilpeak version**: 0.3.1-BETA
 - **Do you reproduce on https://tranquilpeak.kakawait.com demo?**: no
 
### Actual behavior
When using server side highlighting code, the code goes over the block (https://gohugo.io/extras/highlighting/#server-side)

Here is an example: http://imgur.com/a/ImAkC

### Expected behavior
It would be great if the code could stay in the highlight block.

### Steps to reproduce the behavior
Just add an enough long line to see it going outside its zone:
```
{{< highlight yaml >}}
blabla: aaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaa a a a a aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaa
{{< /highlight >}}
```

**Comment by jhabdas** [comment]
`overflow: scroll`

**Comment by deimosfr** [comment]
Hi,

Thanks for the answer but I do not catch where I should put the overflow field. Can you please give more information on that please ?

Thanks

**Comment by kakawait** [comment]
@deimosfr yes is about `overflow` I will check how _Hugo_ generate server side HL to determine where to put the `overflow`

**Comment by jhabdas** [comment]
It's somewhere in this general vicinity:

```
  pre, .highlight pre {}
```

I haven't done the work yet though to carefully look into it. YMMV

**Comment by deimosfr** [comment]
It works thanks !

Here is the override I made:
```css
pre, .highlight pre {
   overflow: scroll;
}
```

**Comment by kakawait** [comment]
@deimosfr (is not related to the issue itself) just stupid question, highlight when using server side has ugly render (because my `css` was not designed for) but on your screenshot your rendering seems better. So did you override/customize `css` already?

**Comment by deimosfr** [comment]
Not at all. If you want to get a look at what I did, you cna check there: https://blog.deimos.fr

**Comment by kakawait** [comment]
@deimosfr I have to add some css so because rendering is not so great :)

**Comment by jhabdas** [comment]
Fork it. It's a Pygments theme roller built with NPM scripts:
https://github.com/comfusion/atom-one-pygments/blob/master/package.json

**Comment by kakawait** [comment]
I was more firstly talking about `padding` and `marging` that is not part of _Pygments_ CSS. Even more it's seems that css is inlined when using _Pygments_ with hugo... at least the color

![screen shot 2017-04-21 at 14 29 52](https://cloud.githubusercontent.com/assets/275609/25277453/03cb92ae-269f-11e7-93fd-24d7d2707090.png)

**Comment by kakawait** [comment]
It's seems to be related to config:

```toml
# true: use pygments-css or false: color-codes directly
pygmentsUseClasses = false
```
