### ISSUE TITLE
Go code highlight: inconsistent comments highlight

### ISSUE THREAD

**Issue by vbauerster** [kakawait/hugo-tranquilpeak-theme#154]
### Configuration

 - **Operating system with its version**: 
macOS Sierra 10.12.4
 - **Browser with its version**:
Chrome Version 57.0.2987.133 (64-bit)
 - **Hugo version**: 
v0.20
 - **Tranquilpeak version**: 
0.3.1-BETA
 - **Do you reproduce on https://tranquilpeak.kakawait.com demo?**:
Yes, see [Go example](https://tranquilpeak.kakawait.com/2015/03/highlighted-code-showcase/#go) line 10.
 

### Actual behavior

When using `{{< codeblock "example.go" "go" >}}` blocks to highlight the code, comments are highlighted inconsistently. Sometimes greyed out correctly, but mostly incorrect:

[![Screen Shot 2017-04-17 at 15.56.10.png](https://s25.postimg.org/rdo1ww9u7/Screen_Shot_2017-04-17_at_15.56.10.png)](https://postimg.org/image/i5vtg72rv/)
[![Screen Shot 2017-04-17 at 15.56.24.png](https://s25.postimg.org/rexzqbbnz/Screen_Shot_2017-04-17_at_15.56.24.png)](https://postimg.org/image/enjtjt1vv/)

Full sample is [here](https://vbauerster.github.io/2017/04/removing-items-from-a-slice-while-iterating-in-go/)

### Expected behavior
Comments should be greyed out everywhere. Like so:
[![Screen Shot 2017-04-17 at 15.56.10.png](https://s25.postimg.org/rdo1ww9u7/Screen_Shot_2017-04-17_at_15.56.10.png)](https://postimg.org/image/i5vtg72rv/)

**Comment by kakawait** [comment]
@vbauerster Could you please try to add following add following JS on your page?

`//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.4.0/languages/go.min.js`

You could you `customJS` parameter to easily integrate inside your current site

```toml
# Inside Param section
# [params]
customJS = ["//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.8.0/languages/go.min.js"]
```

You can validate it by opening page (html) source (or network tab on chrome debug) to validate that script are properly loaded.

I'm not totally sure it will fix. So please gimme feedback

**Comment by jhabdas** [comment]
FWIW it's preferable to always use `https` when available. A protocol-relative URL sent from a server served on `http` will request resources from the CDN over `http`, which is not as secure as sending resources over `https`.

Please also consider always serving external resources from your local machine. While some believe it's faster to serve from CDN, it's papering over the issue the website should be served from a CDN as well.

@vbauerster Here's an alternative CDN with links to many of the languages you may desire. You can download them all in one JS bundle following the instructions provided by the CDN's readme on GitHub: http://www.jsdelivr.com/?query=highlight

**Comment by vbauerster** [comment]
I did as advised, set `customJS`, but there is no any diff in public folder after executing `hugo`.

Looks like sources have no go.min.js file.
[![Screen Shot 2017-04-17 at 17.58.43.png](https://s25.postimg.org/8b4o9yytr/Screen_Shot_2017-04-17_at_17.58.43.png)](https://postimg.org/image/7llvxlya3/)

**Comment by kakawait** [comment]
Could you please upload your config.toml?

**Comment by vbauerster** [comment]
Sure, [here](https://gist.github.com/vbauerster/d327f95d427a8844336be2274ec36090) you are.

**Comment by kakawait** [comment]
You did the same error as issue https://github.com/kakawait/hugo-tranquilpeak-theme/issues/137#issuecomment-293486176

Maybe because you use previous templat of  `config.toml`

You have to place `customJS` before `[params.header.rightLink]` like following

https://gist.github.com/kakawait/95714c03302ea779012b0fd43f9d0b4e

**Comment by vbauerster** [comment]
Thank you for pointing that out, indeed I used the template from v0.3.0-BETA.
I have put `customJS` right before `[params.header.rightLink]`, and run hugo.

`public/index.html` now ends with those lines:
```html
   <script src="https://vbauerster.github.io/https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.8.0/languages/go.min.js"></script>    
  </body>
</html>
```
I suppose script src content is wrong.

**Comment by kakawait** [comment]
Oups my bad I forget that only work with local source file... I will not loose your time more. As soon as I get computer I will check by myself.

And I will open an issue to support both relative and absolute `customJS` and `customCSS`

**Comment by vbauerster** [comment]
That's ok I'm glad to help.

**Comment by kakawait** [comment]
Otherwise you should customize `script.html` to add missing scripts

**Comment by kakawait** [comment]
@vbauerster I fixed issue with `customCSS` and `customJS` in `develop` branch https://github.com/kakawait/hugo-tranquilpeak-theme/pull/156. Could you please try on it? I try myself with basic `go` script that seems to fix comment issue. But my sample was pretty simple

**Comment by vbauerster** [comment]
All comments now greyed out, expect one:
[![Screen Shot 2017-04-17 at 22.46.55.png](https://s25.postimg.org/vhp0pe5sf/Screen_Shot_2017-04-17_at_22.46.55.png)](https://postimg.org/image/sauh5rlcb/)
Strange, the only snippet not highlighted at all.
I have pushed the public to my blog.

**Comment by vbauerster** [comment]
The source of that block is:
```
{{< codeblock "withRange.go" "go" "https://play.golang.org/p/_XAfory3AN" "playground" >}}
func main() {
	for i, p := range people {
		if p.Remove {
			people = append(people[:i], people[i+1:]...)
		}
	}
	fmt.Println(people) // [{P0 false} {P1 false} {P2 false}]
}
{{< /codeblock >}}
```
It is the same as the rest.

**Comment by kakawait** [comment]
that strange because even `withPlainOldForV3.go` was properly rendered. I will try to understand

**Comment by vbauerster** [comment]
Ok, [here](https://gist.github.com/vbauerster/e71dd45150b59364998d2ea1576b6949) is full source md file, if you need it.

**Comment by kakawait** [comment]
And that even more strange that it seems to work as standalone http://jsfiddle.net/z4n5Ltrm/

**Comment by kakawait** [comment]
Ok I found where is the problem, is located on how I apply highlight js https://github.com/kakawait/hugo-tranquilpeak-theme/blob/master/layouts/partials/script.html#L13

I will try to fix it asap, because I can't simply remove that code else line will be bigger than expected

![screen shot 2017-04-18 at 09 44 11](https://cloud.githubusercontent.com/assets/275609/25119731/9c61d090-241b-11e7-9617-1c0e3eefa82b.png)

And will no more align with line number :)

**Comment by kakawait** [comment]
Anyway I wanted to refactor some piece of thing related to HL for https://github.com/kakawait/hugo-tranquilpeak-theme/issues/24

I will done everything

**Comment by kakawait** [comment]
@vbauerster but keep `customJS` with `go` language, you will need it in any case.

**Comment by vbauerster** [comment]
Ok, thank you for support. Waiting for fix 👍

**Comment by kakawait** [comment]
@vbauerster it should be fixed on develop branch. Please pull it again :)

**Comment by vbauerster** [comment]
Yes, now it is ok! Thank you!

**Comment by kakawait** [comment]
@vbauerster you can also use new `customJS` syntax that offer much more options https://github.com/kakawait/hugo-tranquilpeak-theme/blob/develop/docs/user.md#add-custom-js-or-css-using-configuration

Currently on `develop` branch

**Comment by vbauerster** [comment]
I've built my public form develop branch 093011e, with new `customJS` syntax in my `config.toml`.
Now the snippet `withRange.go` is not highlighted anymore in Chrome and Safari. However it is highlighted in Firefox.

**Comment by kakawait** [comment]
Could you test without `defer` and `async` parameters

**Comment by vbauerster** [comment]
It is correct now, without defer and async.

**Comment by kakawait** [comment]
Yes because I think https://github.com/kakawait/hugo-tranquilpeak-theme/blob/develop/layouts/partials/script.html#L17 is not `async` nor `defer` thus is executed before you get `go.min.js`.

Both attr is pretty new for me (since I'm not day to day frontend developer) I have to document more to understand how, where to add such attributes or not :)

**Comment by vbauerster** [comment]
When using both `async` and `defer`, modern browsers will use `async` only. So I set `defer = true` only. Now it works as expected.

**Comment by vbauerster** [comment]
First, `defer` tagged scripts, loads asynchronously and executes after whole HTML document has been loaded. Second, if there are more than one `defer` scripts, ordering will be preserved. For example:
```HTML
<script src="1.js" defer></script>
<script src="2.js" defer></script>
```
Execute order is guaranteed `1.js` then `2.js`. It is useful when script `2.js` depends on `1.js` for example.

**Comment by jhabdas** [comment]
http://stackoverflow.com/questions/8996852/load-and-execute-order-of-scripts/8996894#8996894
