### ISSUE TITLE
Categories set the Chinese language garbled

### ISSUE THREAD

**Issue by sdevil507** [kakawait/hugo-tranquilpeak-theme#166]
**Hello, I really like the template you made!**
**But when I set the category for the Chinese language will appear garbled！**

/content/post/xxx.md:
![step1](http://ohbwj8sru.bkt.clouddn.com/step1.png)

Show results:
![step2](http://ohbwj8sru.bkt.clouddn.com/step2.png)

At present my approach is as follows:

modify hugo-tranquilpeak-theme/layouts/partials/internal/recursive-categories-1.html 

![step3](http://ohbwj8sru.bkt.clouddn.com/step4.png)

But the updated version still needs to be modified.

Is there a better way to solve this problem?

Please help me, thanks！

**Comment by kakawait** [comment]
Thank you for reporting I will fix it asap

**Comment by QuietWind** [comment]
I have same problem @kakawait 
![image](https://cloud.githubusercontent.com/assets/8223607/25780608/862e60f4-335c-11e7-96f5-235f4c677574.png)

**Comment by jhabdas** [comment]
@QuietWind @sdevil507 though I don't want to speak for @kakawait, I do want to mention he has done a tremendous job providing this theme and I feel it would be great if either of you could take this issue to PR to help advance the theme.

**Comment by sdevil507** [comment]
@jhabdas Yeah, you're right.It's really a great project.We should take part in it instead of just asking questions！

@kakawait I found that this is not a problem with your template.
The problem is that we use the MAC OS X.
This problem should be a file encoding problem.
NFC is used in most cases, but in Mac OS's HFS+ file system, normalized to NFD.
I guess it is caused by this problem.
[categories-with-accented-characters](https://discuss.gohugo.io/t/categories-with-accented-characters/505/14)
[https://github.com/spf13/hugo/issues/2203](https://github.com/spf13/hugo/issues/2203)

@QuietWind I hope to help you!

**Comment by jhabdas** [comment]
> I found that this is not a problem with your template.

If there's no problem with the theme, please kindly close this issue.

**Comment by jhabdas** [comment]
❤️

**Comment by jhabdas** [comment]
> Sorry I was on vacancies.

How dare you. LOL
