### ISSUE TITLE
about link's suggestion

### ISSUE THREAD

**Issue by nanjishidu** [kakawait/hugo-tranquilpeak-theme#168]
hi,I'm using your template，very good。。。
I have a suggestion
![category](https://cloud.githubusercontent.com/assets/15984590/25657435/768abb22-3030-11e7-8bf5-66dcdcba4198.png)
![tag](https://cloud.githubusercontent.com/assets/15984590/25657436/76a19d6a-3030-11e7-90a8-90e1974dd86f.png)
If “uglyurls = true”,the links of catagory.html and tag.html need to add ". html".

**Comment by jhabdas** [comment]
Here's what I use in After Dark, though I'm not entirely satisfied with it:

```html
<a href="{{ "/" | relURL }}categories/{{ . | urlize }}/">{{ . }}</a>
```

I believe it has the same problem, which some of the following conversation on the Hugo discussion boards may help point the way towards addressing in a discussion forum:

https://discuss.gohugo.io/t/creating-taxonomic-link-partial-for-multilingual-translations/

**Comment by jhabdas** [comment]
@nanjishidu out of curiosity, are you using ugly URLs? If so, would you kindly provide some justification as to why this should be an issue against Tranquil Peak, and not Hugo themes in general? Also, have you opened a thread on the [Hugo discussion forum](https://discuss.gohugo.io/) to bring this up giving it's a more widespread issue and not specific to Tranquil Peak?

Driving the conversation on the forums will help open @kakawait to more useful development activities as opposed to trying to solve every possible use case. Pareto principle applies here.
