### ISSUE TITLE
How to add latex math formula in the theme

### ISSUE THREAD

**Issue by huyingjie** [kakawait/hugo-tranquilpeak-theme#170]
### Configuration

 - **Operating system with its version**: Mac OS 10.12.4
 - **Browser with its version**: Chrome 58.0.3029.96
 - **Hugo version**: 0.20.7
 - **Tranquilpeak version**: 0.3.1-BETA
 - **Do you reproduce on https://tranquilpeak.kakawait.com demo?**: Yes
 

### Actual behavior

Following the instruction in the page <http://docs.mathjax.org/en/latest/start.html>, I added the following code in `head.html` 

```
    <script type="text/x-mathjax-config">
    MathJax.Hub.Config({
      tex2jax: {inlineMath: [['$','$'], ['\\(','\\)']]}
    });
    </script>
    <script type="text/javascript" async src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML">
    </script>
```
I added math formula `$\beta = \alpha$` in the `md` post

### Expected behavior
Math formula should be shown. But plain text `$\beta = \alpha$` is shown.

### Steps to reproduce the behavior
The same with the actual behavior

**Comment by jhabdas** [comment]
@huyingjie have you tried this in the upstream? If so, what were the results?

**Comment by kakawait** [comment]
@huyingjie  I never use that lib I have to check it how it works and how to integrate with Hugo.

**Comment by huyingjie** [comment]
@jhabdas I use basic elements of latex and do not know what is upstream.

**Comment by huyingjie** [comment]
@kakawait Thank you for you reply. Please check it and add latex to your theme. I do not want to search for a new theme again and again for latex. As a newbie, it is hard for me to achieve what I need because I really do not understand how hugo works.

**Comment by jhabdas** [comment]
> @jhabdas I use basic elements of latex and do not know what is upstream.

The upstream in this case would be the Hexo version of the theme, from whence this came.

**Comment by kakawait** [comment]
@huyingjie Do you really need this piece of code?

```
<script type="text/x-mathjax-config">
    MathJax.Hub.Config({
      tex2jax: {inlineMath: [['$','$'], ['\\(','\\)']]}
    });
</script>
```

Else you can add any external JS script using `customJS` config properties.

I ask question due to following PR that is not using that piece of code https://github.com/kakawait/hugo-tranquilpeak-theme/pull/191

**Comment by huyingjie** [comment]
@kakawait Which hugo and tranquilpeak version do you use?
I followed the instruction in the official website of Hugo which requires adding the codes. 
I do not know JS script.

**Comment by huyingjie** [comment]
@kakawait 

I add 
```
<script src="//yihui.name/js/math-code.js"></script>
<script async
src="//cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML">
</script>
```
before `</body>` in the file `foot.html`

`$$ \alpha $$` is shown as a math symbol but `$ \alpha $` is not

**Comment by maireh** [comment]
I was able to MathJax very easily. I added it to the footer instead of the header. I admit that I copied the code from the Academic theme. I also added a math parameter (the same as Academic). 

I love your theme! I just discovered Hugo last week and since then I have been playing with the themes. Yesterday I settled on tranquilpeak. I am so happy.

**Comment by kakawait** [comment]
@huyingjie and @maireh I will fix that issue for `0.4.4-BETA`. I think I will look what _Academic_ theme is doing and copied it if necessary!

Sorry for delay I was really busy. I hope you're still using _Tranquilpeak_

**Comment by AbangSD** [comment]
I add
``` html
<script type="text/javascript" async
  src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
  MathJax.Hub.Config({
    tex2jax: {
        inlineMath: [['$','$'], ['\\(','\\)']],
        processEscapes: true
      }
  });
  MathJax.Hub.Queue(function() {
    var i, text, code, codes = document.getElementsByTagName('code');
    for (i = 0; i < codes.length;) {
      code = codes[i];
      if (code.parentNode.tagName !== 'PRE' &&
          code.childElementCount === 0) {
        text = code.textContent;
        if (/^\\\((.|\s)+\\\)$/.test(text) ||
            /^\$(.|\s)+\$$/.test(text) ||
            /^\\begin\{([^}]+)\}(.|\s)+\\end\{[^}]+\}$/.test(text)) {
          code.outerHTML = code.innerHTML;  // remove <code></code>
          continue;
        }
      }
      i++;
    }
    });
</script>
```
in the file footer.html
It can't work nice sometimes.
For example, because I need a complicated form, I used the latex table, but it doesn't work.
Looking forward to see the new version of this great theme!
And Tranquilpeak is really wonderful.

**Comment by AbangSD** [comment]
When I use the mmark, it works well.
