### ISSUE TITLE
[Help/Question] Adding a table of contents to posts

### ISSUE THREAD

**Issue by Verric** [kakawait/hugo-tranquilpeak-theme#175]
Hi,

I'm trying to add a "table of contents" to some of my posts, however I can't seem to get it to work :(

I've found the following under `src/layout/_default/single.html`
```go
  <div class="post-content markdown" itemprop="articleBody">
            <div class="main-content-wrap">
              {{ (replaceRE "<!--\\s*[t|T][o|O][c|C]\\s*-->" (printf "<h1 id=\"table-of-contents\">%s</h1>%s" (i18n "post.toc") .TableOfContents) .Content) | safeHTML }}
              {{ partial "post/gallery.html" . }}
            </div>
          </div>
```
So it would be my guess that in my post, I could do something like the following

```markdown
+++
Front-matter
+++

# Header

<!--[TOC]-->

### Sub-header 1

### Sub-header 2
```

and it should generate  a table of contents ?

Any help would be appreciated :)

**Comment by jose-oc** [comment]
On your content file type just: 

`<!-- toc -->`

**Comment by Verric** [comment]
Ahh I was so close.
Thanks for your help :)
