### ISSUE TITLE
[Developper documentation] - Is bower still used ?

### ISSUE THREAD

**Issue by Niceplace** [kakawait/hugo-tranquilpeak-theme#176]
Current [developer documentation](https://github.com/kakawait/hugo-tranquilpeak-theme/blob/master/docs/developer.md#installation) mentions at the installation, step 7 that `bower install` should be run to install dependencies.

However, I notice that no bower.json file not present at the root of the directory.

I assume that bower has been replaced by an npm script ? I'm getting this feeling from reading [this comment](https://github.com/kakawait/hugo-tranquilpeak-theme/issues/159#issuecomment-294729863) in #159.

Would it be possible to update developer documentation to reflect this change ?

Thanks a lot and thanks for the great theme ! :) I'm building my blog with it and I'm really eager to see the final product !

**Comment by kakawait** [comment]
@Niceplace Yeah `bower` was used but I removed it, I will fix documentation since is no used anymore
