### ISSUE TITLE
does this theme have support for multilingual sites?

### ISSUE THREAD

**Issue by gideondsouza** [kakawait/hugo-tranquilpeak-theme#177]
Hi, 

Just a simple question. Is this theme language friendly. Will it have support for two languages?

 - **Operating system with its version**: Linux - Fedora 25. 
 - **Browser with its version**:  Google Chrom 58.0.3029.110
 - **Hugo version**: Hugo Static Site Generator v0.21-DEV linux/amd64 BuildDate: 2017-05-21T11:31:27+05:30
 - **Tranquilpeak version**: N/A
 - **Do you reproduce on https://tranquilpeak.kakawait.com demo?**: N/A

**Comment by kakawait** [comment]
Hello @gideondsouza this theme support translation however I didn't test myself to setup site using multiple lang. I think it will not working as built-in.

**Comment by gideondsouza** [comment]
I see. Alright. thanks for your reply.

**Comment by henningsway** [comment]
has there been some success with setting tranquilpeak up for a multilingual site so far?

**Comment by kakawait** [comment]
@henningsway I have not tested by myself even if I'm the author. The only thing I tested and working is translation. But we/I have to test multi-lingual site since it's supported by Hugo but maybe some stuff to do on theme
