### ISSUE TITLE
Thumbnail image not working properly

### ISSUE THREAD

**Issue by juliazhang95** [kakawait/hugo-tranquilpeak-theme#179]
### Configuration

 - **Operating system**: Windows 10  Version 1607
 - **Browser with its version**: Google Chrome Version 58.0.3029.110 (64-bit)
 - **Hugo version**: 0.21
 - **Tranquilpeak version**: 0.3.1-BETA
 - **Do you reproduce on https://tranquilpeak.kakawait.com demo?**: No - the thumbnails work properly
 

### Actual behavior
In config,toml I've set the default thumbnailImagePosition to "left" but a large picture is showing up on the bottom instead. 
![thumbnail](https://user-images.githubusercontent.com/11791012/27016995-ebf9e4d8-4ef2-11e7-8869-4d5cb18f38bd.PNG)
I tried this on a fresh new hugo site and the tranquilpeak with no modifications other than changing the thumbnailImagePosition from "bottom" to "left", and then restarting the server.

In the front matter of my test post, I've just added the coverImage field.
```
---
title: "New Post"
date: 2015-05-28
categories:
- category
- subcategory
tags:
- tag1
- tag2
keywords:
- tech
coverImage: http://cdn-image.travelandleisure.com/sites/default/files/styles/1600x1000/public/1477342854/positano-amalfi-coast-italy-AMALFI1024.jpg?itok=Aa5bXDAF
---

<!--more-->
```

 I'm not sure if this is a bug, or if I'm just not doing something.

**Comment by kakawait** [comment]
Hello @juliazhang95 thank you for reporting. I will check that asap

**Comment by kakawait** [comment]
@juliazhang95 Confirmed. For instance you can use following workaround:

Use [Front matter settings](https://github.com/kakawait/hugo-tranquilpeak-theme/blob/master/docs/user.md#front-matter-settings) rather than global setting like following

```
---
title: "New Post"
date: 2015-05-28
categories:
- category
- subcategory
tags:
- tag1
- tag2
keywords:
- tech
coverImage: http://cdn-image.travelandleisure.com/sites/default/files/styles/1600x1000/public/1477342854/positano-amalfi-coast-italy-AMALFI1024.jpg?itok=Aa5bXDAF
thumbnailImagePosition: left
---

<!--more-->
```

I will try to fix it asap
