### ISSUE TITLE
How to use Algolia search

### ISSUE THREAD

**Issue by yannxia** [kakawait/hugo-tranquilpeak-theme#180]
### Configuration

 - **Win10 64**: 
 - **Chrome 58.0.3029.110 (64-bit)**:
 - ** v0.22.1 windows/amd64**
 - **0.3.1-BETA**:
 - **yes**:
 
### Actual behavior
Show Algolia Search page...
but demo has it.  [demo](http://louisbarranqueiro.github.io/hexo-theme-tranquilpeak
). and i find demo has a js file is  http://cdn.jsdelivr.net/algoliasearch/3/algoliasearch.min.js.
But i'm not, and docs can't find any.....

### Expected behavior
None thing.

### Steps to [reproduce]([url](url)) the behavior

ADD
```

[[menu.main]]
  weight = 4
  identifier = "search"
  name = "Search"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-search\"></i>"
  url = "/#search"
  class = "st-search-show-outputs"

```

**Comment by kakawait** [comment]
Hello @yannxia, unfortunately algolia is not yet supported on this theme see #8 (closed as dup)
