### ISSUE TITLE
Configuring sharing options

### ISSUE THREAD

**Issue by hellt** [kakawait/hugo-tranquilpeak-theme#181]
In the original Hexo theme there is config blob that allows you to add/disable different [sharing options](https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/blob/master/docs/user.md#sharing-options) -- facebook, twitter, etc.

This port seems has no example on how to do so. Or am I missing something?

**Comment by kakawait** [comment]
Currently in progress not yet released sorry, see https://github.com/kakawait/hugo-tranquilpeak-theme/pull/147

**Comment by hellt** [comment]
Got it, thanks

**Comment by kakawait** [comment]
There is no much work, just so stuff to do to integrate sharing option with translation mechanism :)
