### ISSUE TITLE
yaml syntax highlighting problems when using code fences

### ISSUE THREAD

**Issue by hellt** [kakawait/hugo-tranquilpeak-theme#186]
### Configuration

 - os x 10.10.9: 
 - **Hugo version**: 0.20.2
 - **Tranquilpeak version**: 0.3.1 BETA
 - **Do you reproduce on https://tranquilpeak.kakawait.com demo?**: N/A
 
### Actual behavior
yaml syntax is unrecognized when using code fences like:
```
<triple backtick>yaml
 yaml code
<triple backtick>
```

### Expected behavior
YAML syntax applied

**Comment by kakawait** [comment]
@hellt I have to check if not an Hugo issue directly. Because theme does not handle directly code fences syntax

**Comment by kakawait** [comment]
@hellt Is not really an issue since default _Highligth.js_ package do not cover `yaml` syntax, as you can see on download page https://highlightjs.org/download/

You must add `yaml.js` _Highligth.js_ add-on, to do that you can simply add following configuration inside your `config.toml`

```
[[params.customJS]]
    src = "https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/languages/yaml.min.js"
    integrity = "sha256-tvm0lHsuUZcOfj/0C9xJTU4OQx5KpUgxUcAXLX5kvwA="
    crossorigin = "anonymous"
    async = true
    defer = true
```

**Comment by hellt** [comment]
Thanks, will check this today-tomorrow

**Comment by hellt** [comment]
a tiby question, how did you find the js for yaml lang?

**Comment by kakawait** [comment]
Sure, here https://cdnjs.com/libraries/highlight.js/

**Comment by hellt** [comment]
@kakawait do you know if it is possible to add the same way custom hljs theme?
I tried:
```
  [[params.customCSS]]
      src = "https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/vs.min.css"
      integrity = "sha256-w6kCMnFvhY2tI1OnsYR/rb5DG9yFGodJknvFZOkp51E="
      crossorigin = "anonymous"
      async = true
      defer = true
```
But seems like the builtin styles are overriding

**Comment by hellt** [comment]
I added kinda end-2-end instruction for this adjustments.
Would like to see a more simplified, or automated way to add custom HLjs themes to Tranquilpeak.

Thanks, this issue can be closed

**Comment by kakawait** [comment]
@hellt Yes I will think about to externalize HL theme to be more easy to change it

**Comment by kakawait** [comment]
@hellt I will close that issue and open a new one for easy customization HLjs theme

**Comment by hellt** [comment]
while this is somehow related to that issue, can you please shed some light why in Chrome, YAML code blocks are not properly rendered, while it is ok in latest stable firefox and IE?

What I see, is the YAML fenced codeblock has different CSS class properties:
![image](https://user-images.githubusercontent.com/5679861/33255343-2bd90742-d35e-11e7-8846-187bd3f424ac.png)

The same code block in firefox:
![image](https://user-images.githubusercontent.com/5679861/33255369-4521e8fe-d35e-11e7-93de-1eec2f5e35af.png)


As you see, no `codeblock` and `hljs` classes are applied, and code block content has not been parsed to different elements

At the same time, using a local hugo server in the same Chrome browser all is good

**Comment by kakawait** [comment]
I will check that.

**Comment by kakawait** [comment]
@hellt I confirm the bug... It's really strange that is working on FF and not Chrome. I will update you asap when I get something

**Comment by kakawait** [comment]
@hellt Could you share with me your `.md` file of that blog post? https://netdevops.me/2017/how-to-add-yaml-highlight-in-highlight.js/

**Comment by hellt** [comment]
Sure - https://gitlab.com/rdodin/netdevops.me/blob/master/content/post/2017/yaml_hljs.md

**Comment by kakawait** [comment]
Thank you, now I have to find a way to reproduce locally lol :)

@hellt In parallel could you please try to remove tweak following parameters:

```
async = true
defer = true
```

Try with both to `false`, if it works you can try with 1 `false` and 1 other `true`.

I suspect that `async` and `defer` attribute will cause that DOM will be successfuly loaded before script will be apply that why highlighting does not work since JS is not 100% loaded.

**Comment by hellt** [comment]
tried with both async and defer set to false, no effect. Currently my blog is configured with `false` for both these params so you can check it out yourself if there is something interesting

**Comment by kakawait** [comment]
Ok thank you, sorry for that issue. I will try to find what's happen.

The fact is working on local is really strange. That why I suspected loading order issue.

**Comment by kakawait** [comment]
@hellt issue comes from `async="false"` I suspect that Chrome still `async` even if equals to false because I'm not sure that `async` attr allow value. I mean is `<script async src="...">` common usage without value.

I have to fix it

**Comment by kakawait** [comment]
As workaround you can use older (_deprecated_) syntax describe here https://github.com/kakawait/hugo-tranquilpeak-theme/blob/master/docs/user.md#customization

```toml
[params]
  customJS = ["https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/languages/yaml.min.js"]
```

**Comment by hellt** [comment]
Thanks! Is this something that you can fix or does it demand fixing the
upstream code?

On Wed, Nov 29, 2017 at 11:50 PM, Thibaud Lepretre <notifications@github.com

**Comment by kakawait** [comment]
Is something that i can fix. It will be plan for next release `0.4.4-BETA` but you could try work around before that futur release

**Comment by hellt** [comment]
Thanks, this worked for Chrome
