### ISSUE TITLE
Request to add my blog to the showcase

### ISSUE THREAD

**Issue by zentechnista** [kakawait/hugo-tranquilpeak-theme#189]
Hi! Putting a request to add my blog to the Tranquilpeak theme showcase:

URL: https://zentechnista.github.io/
Name: Zentechnista
Description: Personal blog where I write about Go, web design, and learning to code as a self-taught learner.

**Comment by kakawait** [comment]
@zentechnista Thank you for choosing this theme.

I will add to showcase asap

**Comment by kakawait** [comment]
Just added to the https://github.com/kakawait/hugo-tranquilpeak-theme/wiki/Showcase 

Thank you

**Comment by zentechnista** [comment]
Great, thank you!
