### ISSUE TITLE
Add my blog into the showcase

### ISSUE THREAD

**Issue by robinfhu** [kakawait/hugo-tranquilpeak-theme#193]
I'm using the Hugo Tranquilpeak theme you made for my blog.  

URL: [http://robinforest.net](http://robinforest.net)
Name: 'Robin Hu'

Great work!

**Comment by kakawait** [comment]
Hi @robinfhu Thank you for your interest. I will add it asap

**Comment by kakawait** [comment]
Just added to the https://github.com/kakawait/hugo-tranquilpeak-theme/wiki/Showcase

Thank you
