### ISSUE TITLE
Can't add new sharing option

### ISSUE THREAD

**Issue by Youkoulayley** [kakawait/hugo-tranquilpeak-theme#195]
### Configuration

 - **Operating system with its version**: Debian 8 
 - **Browser with its version**: Firefox 55
 - **Hugo version**: 0.26
 - **Tranquilpeak version**: 0.3.1
 - **Do you reproduce on https://tranquilpeak.kakawait.com demo?**: Can't test :p
 

### Actual behavior
I have those sharing options in my posts :
![IMG](https://i.imgur.com/jNGgP8e.png)

### Expected behavior
In my config.toml, I have added this : 
```
  [[params.sharingOptions]]
    name = "Linkedin"
    icon = "fa-linkedin"
    url = "https://www.linkedin.com/shareArticle?url=%s"
```

But as you can see, it doesn't work :/

**Comment by kakawait** [comment]
@Youkoulayley I just tried I got no issue with you're piece of conf.

Could you please upload whole `config.toml`

However there is a regression on link generation, I will fix it soon.

**Comment by Youkoulayley** [comment]
I was using `git submodule` to get the repo, but I didn't know that it doesn't fetch the last commit. I will read the doc to get throught this problem. It works really great with a git clone and the 0.4.1-BETA.

Thank you !
