### ISSUE TITLE
how to modify the number of post been showed per page?

### ISSUE THREAD

**Issue by fanvinga** [kakawait/hugo-tranquilpeak-theme#207]
Hi~
Could you please answer me a question about how to modify the number of post been showed per page?

**Comment by fanvinga** [comment]
Configuration

OS: macOS 10.12.6
Chrome 62.0.3202.38
Hugo 0.29
TranquilPeak 0.4.1-beta
Reproduce in demo? Yes


Click Archives

**Comment by kakawait** [comment]
@fanvinga Did you try https://gohugo.io/templates/pagination/ ?

Change your `config.toml` to add:

```toml
Paginate = 20
```

**Comment by fanvinga** [comment]
Ops..I was too careless :(
After you reminding me, i found that "Paginate = 7" in config.toml.
Thank you so much 👍
