### ISSUE TITLE
adding mailto:

### ISSUE THREAD

**Issue by Ads7** [kakawait/hugo-tranquilpeak-theme#208]
Wish to add a mailto:abc@gmail.com in menu links simply adding that to URL appends it with the host URL. Could you guide how to go about it

**Comment by kakawait** [comment]
@Ads7 did you try with `url = "mailto:abc@gmail.com"` on menu link param (I didn't test by myself)

```
[[menu.links]]
  weight = 1
  identifier = "email"
  name = "Email me"
  url = "mailto:abc@gmail.com"
```

**Comment by AlexandreCantin** [comment]
I've tried by my side ```url="mailto:..."``` and it's not working...
I've fixed this issue by editing menu.html (line 3)

```
    {{ if and (or (in .URL "://") (in .URL "mailto:")) (not (in .URL (printf "%s" $.root.Site.BaseURL))) }}
```

**Comment by kakawait** [comment]
@AlexandreCantin Thank for you feedback I will add it on theme

**Comment by xiaoyunyang** [comment]
The suggested solution above causes a new tab to be opened when `mailto` is clicked. Instead of combining the `mailto` stuff with the external link stuff, a new if branch should be created just for `mailto`:

```
{{ if and (in .URL "mailto:") (not (in .URL (printf "%s" $.root.Site.BaseURL))) }}
<a class="sidebar-button-link {{ if eq .Identifier "search" }}open-algolia-search{{ end }}" href="{{ .URL | safeURL }}" rel="noopener">
{{ else if and (in .URL "://") (not (in .URL (printf "%s" $.root.Site.BaseURL))) }}
<a class="sidebar-button-link {{ if eq .Identifier "search" }}open-algolia-search{{ end }}" href="{{ .URL | safeURL }}" target="_blank" rel="noopener">
```
