### ISSUE TITLE
Accronym and abbr rendering buggy

### ISSUE THREAD

**Issue by kakawait** [kakawait/hugo-tranquilpeak-theme#223]
<img width="749" alt="screen shot 2017-11-01 at 11 33 41" src="https://user-images.githubusercontent.com/275609/32271078-9f04e42c-bef8-11e7-9ac7-ce12ac28243e.png">

https://tranquilpeak.kakawait.com/2015/05/elements-showcase/

**Comment by yamila-moreno** [comment]
Hi! I've looked at this bug, but I'm not sure I understood properly the problem. If you mean the double dotted line, I tested removing the css of acronym and abbr in `src/scss/base/_base.scss` (lines 152-154) and it leaves just one line. If this is what you meant, I can do the PR. Cheers!

![abbr](https://user-images.githubusercontent.com/3340793/33035679-4d327b3a-ce2c-11e7-990f-62e70f36f53f.png)

**Comment by yamila-moreno** [comment]
On it
