### ISSUE TITLE
Consider adding showcases post on example site tranquilpeak.kakawait.com

### ISSUE THREAD

**Issue by kakawait** [kakawait/hugo-tranquilpeak-theme#230]

**Comment by yamila-moreno** [comment]
Hi! I offer myself to to this issue, if you could provide more information about the task.

Should I create a blogpost with the exact same content as https://github.com/kakawait/hugo-tranquilpeak-theme/wiki/Showcase ?

I could also do #228 (which is my own blog)

Best!

**Comment by kakawait** [comment]
@yamila-moreno first thank you for spending your time on that theme.

You totally right i want to create a blog post (and may listed at least on first pagination page, i though about being the second post) with every blog using tranquilpeak theme.

You're not to copy how blog was displayed on wiki. You are free to do whatever on term of presentation.

In addition yes i will be cool if you can report existing and add your from issue you linked. Except if existing is 404 or not using anymore theme.

You can do using pure HTML or md and be part of folder exampleSite which is using for generating https://tranquilpeak.kakawait.com

**Comment by yamila-moreno** [comment]
On it!
