### ISSUE TITLE
Add prism.js support 

### ISSUE THREAD

**Issue by adeleglise** [kakawait/hugo-tranquilpeak-theme#24]
Hi,

Is it possible to use another code block type ? 

The one currently used isn't very "sexy".

**Comment by kakawait** [comment]
@adeleglise what do you mean? 

Can you share any reproduction steps or image or articles posts (.md)?

**Comment by adeleglise** [comment]
Right now the code block style looks like this : 
http://res.cloudinary.com/alaintno/image/upload/v1479059096/Capture-code-block_zjsn3i.png

I am expeting something like prism.js : [http://prismjs.com/](url)

**Comment by kakawait** [comment]
yes but what's wrong for you?

1. Font style
2. Code highlighting
3. Container box css 

About code highlight, this theme is using https://highlightjs.org/ that seems to be more powerful on bash syntax than prism.js

**Comment by kakawait** [comment]
@adeleglise what I can do is following:

1. Fix font style on windows to have better font
2. Add support of `prism.js` in addition to `highlight.js`

that will be ok for you? If you need more `css` changes please explain me your wishes

**Comment by adeleglise** [comment]
Sorry for the delay.

> 
    Fix font style on windows to have better font
    Add support of prism.js in addition to highlight.js

That would be great ! Thanks a lot !

**Comment by kakawait** [comment]
I postponed to `0.2.1-ALPHA` because much more work that I tough.

**Comment by kakawait** [comment]
with following PR https://github.com/kakawait/hugo-tranquilpeak-theme/pull/160 it will be now easy to add `prismjs`
