### ISSUE TITLE
Unable to load Disqus

### ISSUE THREAD

**Issue by Brinkhuis** [kakawait/hugo-tranquilpeak-theme#241]
### Configuration

 - **Windows 10 64 bit**
 - **Google Chrome version 62 and Microsoft Edge**
 - **Hugo Static Site Generator v0.31 windows/amd64 BuildDate: 2017-11-25T19:30:20+01:00**
 - **0.4.3-BETA**
 

### Actual behavior
I created a new post on my site [brinkhuis.github.io](https://brinkhuis.github.io) from RStudio with blogdown::new_post("Web Scraping and Visualizing Data from Coolblue") but cannot get Disqus working. It keeps giving the message "We were unable to load Disqus. If you are a moderator please see our troubleshooting guide."

I put my disqusShortname ("https-brinkhuis-github-io") in the config.toml and added `brinkhuis.github.io` and `disqus.com` as trusted sites.

```
baseURL = "https://brinkhuis.github.io"
languageCode = "en-us"
defaultContentLanguage = "en-us"
title = "My Blog"
theme = "hugo-tranquilpeak-theme"
disqusShortname = "https-brinkhuis-github-io"
# googleAnalytics = "UA-123-45"
paginate = 7
canonifyurls = true
```

Am I missing something here?

### Expected behavior
Disqus to be displayed (on page [https://brinkhuis.github.io/2017/11/web-scraping-and-visualizing-data-from-coolblue](https://brinkhuis.github.io/2017/11/web-scraping-and-visualizing-data-from-coolblue))

### Steps to reproduce the behavior

**Comment by kakawait** [comment]
@Brinkhuis do you configure your `baseURL` `config.toml`?

**Comment by kakawait** [comment]
Ok thank for confirmation.

The only diff I can see from https://tranquilpeak.kakawait.com is about `this.page.url` 

<img width="911" alt="screen shot 2017-11-26 at 19 46 29" src="https://user-images.githubusercontent.com/275609/33243254-bba948fe-d2e2-11e7-910d-f802a9283b1a.png">

where in your case is not an _URL_ but only a path

<img width="732" alt="screen shot 2017-11-26 at 19 48 22" src="https://user-images.githubusercontent.com/275609/33243255-c92295f8-d2e2-11e7-8f93-ab3ec859580e.png">

I have to find why, in addition that I'm using `.Permalink` variable that should be standard/built-in https://github.com/kakawait/hugo-tranquilpeak-theme/blob/master/layouts/partials/script.html#L38

**Comment by kakawait** [comment]
@Brinkhuis Could you please gimme the `hugo` cli command are you using to generate?

**Comment by Brinkhuis** [comment]
I generate from RStudio, using the command `blogdown::serve_site()`

**Comment by kakawait** [comment]
I'm not a _RStudio_ or _Blogdown_ expert but from what I can see https://github.com/rstudio/blogdown/issues/93#issuecomment-297244046

You should use `build_site()` instead as linked command suggest

**Comment by Brinkhuis** [comment]
I tried generating with 'build_site()' but that give the same result.

Is there a setting in `config.toml` to 'correct' my `this.page.url` value?

**Comment by Brinkhuis** [comment]
My page now seems right now...

```
      <script>
        var disqus_config = function () {
          this.page.url = 'https:\/\/brinkhuis.github.io\/2017\/11\/web-scraping-and-visualizing-data-from-coolblue\/';
          
            this.page.identifier = '\/2017\/11\/web-scraping-and-visualizing-data-from-coolblue\/'
          
        };
        (function() {
          
          
          if (window.location.hostname == "localhost") {
            return;
          }
          var d = document, s = d.createElement('script');
          var disqus_shortname = 'https-brinkhuis-github-io';
          s.src = '//' + disqus_shortname + '.disqus.com/embed.js';

          s.setAttribute('data-timestamp', +new Date());
          (d.head || d.body).appendChild(s);
        })();
      </script>
```

**Comment by kakawait** [comment]
@Brinkhuis Now with that code _Disqus_ works for me on https://brinkhuis.github.io/2017/11/web-scraping-and-visualizing-data-from-coolblue/

**Comment by Brinkhuis** [comment]
I see, great! I will add a new post and see if it will also work there...

**Comment by kakawait** [comment]
About your question, I was answered before you update thread.

> Is there a setting in config.toml to 'correct' my this.page.url value?

For _Disqus_ only `baseURL` and `disqusShortname` are mandatory and you filled both correctly

**Comment by Brinkhuis** [comment]
With the setting `relativeurls = true` in `config.toml` and using the command  `blogdown::build_site(local=FALSE)` from `RStudio` everything seems allright!  

Thanks for your time and help!

**Comment by kakawait** [comment]
@Brinkhuis Ok if it's ok for you I will close that issue, feel free to re-open if relevant

Thank you for using _Tranquilpeak_ and have fun
