### ISSUE TITLE
Add my blog into the showcase

### ISSUE THREAD

**Issue by Dehong1** [kakawait/hugo-tranquilpeak-theme#247]
I'm using the Hugo Tranquilpeak theme you made for my blog.

URL: https://dehong.rbind.io/
Name: 'Blog|德宏'

Great work!

**Comment by kakawait** [comment]
@Dehong1 Happy new year

But currently if I browse to https://dehong.rbind.io/ I find something that does not look like _hugo tranquilpeak theme_, may I miss something?

**Comment by Dehong1** [comment]
I only added a cover for my blog.When you click the cartoon figure，you will find hugo tranquilpeak theme,but I don't know whether what I do is right or not.Thank you!
