### ISSUE TITLE
Add my blog into the showcase

### ISSUE THREAD

**Issue by yamila-moreno** [kakawait/hugo-tranquilpeak-theme#250]
Hey, add my blog into the showcase:

    public url                    - https://dendarii.es
    name (optional)         - Viajes dendarii
    description (optional) - Travel blog of Yamila Moreno

thanks!! 
![dendariies](https://user-images.githubusercontent.com/3340793/34469274-8eb8c09a-ef1b-11e7-9587-fc16030d5a62.png)

**Comment by kakawait** [comment]
@yamila-moreno Happy new year 🎉 

Thank for using and contributing (and sorry to be a bit busy and not able to answer or fix thing more quickly, but I've appreciated your help)  to _Hugo tranquilpeak_

I will add to showcase asap

**Comment by yamila-moreno** [comment]
Happy new year for you too!!! No worries about being quick or slow, we all have a life :D 
I had my techie blog with tranquilpeak, but now I put the theme in my travel blog, I really like it! And it had an awesome feedback 👍

**Comment by konbotz** [comment]
Fantastic!

How did you change the image on the sidebar menu? I want to change mine but can't figure it out - even after reading the documentation

**Comment by yamila-moreno** [comment]
Hi @konbotz you have to change the `coverImage` url in `[params]` section in the `config.tom` file.

**Comment by kakawait** [comment]
Added :)
