### ISSUE TITLE
favicon only appearing on the home page

### ISSUE THREAD

**Issue by Ozan147** [kakawait/hugo-tranquilpeak-theme#253]
Thank you for the great theme!

Could you please help with a uniform favicon?

https://www.contrepieds.com/

**Comment by kakawait** [comment]
@Ozan147 Thank you for reporting.

https://www.contrepieds.com/ is down do you think is possible to get it up again?

**Comment by Ozan147** [comment]
https://www.contrepieds.com/ is up and running now

**Comment by aphe** [comment]
i fix this by change the code at `layouts/partials/head.html` line [35](https://github.com/kakawait/hugo-tranquilpeak-theme/blob/907866f6dbe76970371750cae96a4462cb0d21a4/layouts/partials/head.html#L35) with

```html
{{ with .Site.Params.favicon }} <link rel="icon" href="{{ . | absURL }}"> {{ end }}
```

**Comment by kakawait** [comment]
I don't really understand why the current version is not working instead of your fix
