### ISSUE TITLE
a problem about the blog's show effect

### ISSUE THREAD

**Issue by gaoyaqiu** [kakawait/hugo-tranquilpeak-theme#254]
After I installed the blog, the show effects goes like 
![image](https://user-images.githubusercontent.com/8586794/34949675-c0c19fc2-fa4b-11e7-91b9-fc5f9d317890.png)
，not the same as 
![image](https://user-images.githubusercontent.com/8586794/34949715-dd5b0682-fa4b-11e7-8409-c743ad4ebf29.png)

，how to make my show effect the same as the demo's effect show.
thank you for your answering ^_^

**Comment by kakawait** [comment]
@gaoyaqiu Hi

Did you try to tune `sidebarBehavior` configuration (ex https://github.com/kakawait/hugo-tranquilpeak-theme/blob/master/exampleSite/config.toml#L136) 

Try `2` or `3`

**Comment by gaoyaqiu** [comment]
Set to 2 very good.
Thanks.
