### ISSUE TITLE
default highlight support more language

### ISSUE THREAD

**Issue by v1c77** [kakawait/hugo-tranquilpeak-theme#255]
### Configuration
 > all of these configuration is irrelevant.
 - **Operating system with its version**: 
 - **Browser with its version**:
 - **Hugo version**: 
 - **Tranquilpeak version**: 
 - **Do you reproduce on https://tranquilpeak.kakawait.com demo?**:
 

### Actual behavior
tranquilpeak-theme use custom highlight.js witch did't support golang and Swift,
But the related css style has been included .

### Expected behavior
Default highlight.js locate at [cdn](https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js) support more language.

### Steps to reproduce the behavior
The demo blog with tag `go` and `swift`.  -> [Here](https://tranquilpeak.kakawait.com/2015/03/highlighted-code-showcase/)

**Comment by v1c77** [comment]
The way to add param worked for me. Thank u.

**Comment by kakawait** [comment]
Glad to heard is working. I'm closing. Re-open if needed
