### ISSUE TITLE
How to add a page ?

### ISSUE THREAD

**Issue by boeledi** [kakawait/hugo-tranquilpeak-theme#265]
Hi,

I tried to add a contact page.
I followed your instructions but it does not seem to work.

In /content, I have 
/content/page/contact.md

In /layouts/partials/contact.html

In the config.toml, I added a menu:
[[menu.main]]
  weight = 7
  identifier ="Contact"
  name = "Contact"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-envelope\"></i>"
  url = "/page/contact/"

I can access the contact page, but its content is not filled with the /layouts/partials/contact.html.

In Chrome developer tools, I have the following error:
script-qi9wbxp2ya2j6p7wx1i6tgavftewndznf4v0hy2gvivk1rxgc3lm7njqb6bz.min.js:1 Uncaught TypeError: Cannot read property 'top' of undefined
    at b.swipePostBottomBar (script-qi9wbxp2ya2j6p7wx1i6tgavftewndznf4v0hy2gvivk1rxgc3lm7njqb6bz.min.js:1)
    at b.run (script-qi9wbxp2ya2j6p7wx1i6tgavftewndznf4v0hy2gvivk1rxgc3lm7njqb6bz.min.js:1)
    at HTMLDocument.<anonymous> (script-qi9wbxp2ya2j6p7wx1i6tgavftewndznf4v0hy2gvivk1rxgc3lm7njqb6bz.min.js:1)
    at i (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at Function.ready (jquery.min.js:2)
    at HTMLDocument.J (jquery.min.js:2)

Could you please help me ?

**Comment by xiaoyunyang** [comment]
Why do you have a contact.html? The html is created from the markdown file contact.md.

In your contact.md, make sure the [front matter](https://gohugo.io/content-management/front-matter/) contains the following line:

```
showPagination: false
```
This will make the swipePostBottomBar error go away.

**Comment by fu-sen** [comment]
This structure often plagues us. try:

content:
/content/contact/_index.md

layouts:
/layouts/contact/contact.html

hugo server:
http&#58;//localhost:1313/contact/

**Comment by kakawait** [comment]
I close due to lack of feedback. Please re-open if needed
