### ISSUE TITLE
Add my blog into the showcase

### ISSUE THREAD

**Issue by xiaoyunyang** [kakawait/hugo-tranquilpeak-theme#266]
Please consider my website for the showcase. Thank you for the amazing work on this awesome template!

Public Link:  http://xiaoyunyang.github.io/

**Comment by kakawait** [comment]
@xiaoyunyang Thank for using _Hugo tranquilpeak theme_ I will add your blog to showcase on next release

**Comment by ragasirtahk** [comment]
Please consider my blog as well: https://www.ragasirtahk.tk

**Comment by kakawait** [comment]
Both added :)
