### ISSUE TITLE
Open graph url is malformed

### ISSUE THREAD

**Issue by xiaoyunyang** [kakawait/hugo-tranquilpeak-theme#267]
### Configuration

 - **Browser with its version**: Chrome
 - **Hugo version**: v.0.38.1
 - **Tranquilpeak version**: 0.4.3-BETA
 - **Do you reproduce on https://tranquilpeak.kakawait.com demo?**: Yes
 

### Actual behavior
`og:url` is a relative url rather than a canonical url. For instance, if you use Facebook's [open graph object debugger](https://developers.facebook.com/tools/debug/og/object/) on [https://tranquilpeak.kakawait.com/2015/06/welcome-to-tranquilpeak-0.4.3-beta/](https://tranquilpeak.kakawait.com/2015/06/welcome-to-tranquilpeak-0.4.3-beta/), you get this warning:

>Object at URL 'https://tranquilpeak.kakawait.com/2015/06/welcome-to-tranquilpeak-0.4.3-beta/' of type 'blog' is invalid because the given value '/2015/06/welcome-to-tranquilpeak-0.4.3-beta/' for property 'og:url' could not be parsed as type 'url'.

In the HTML `<head>`, you have the following:

```
<meta property="og:url" content="/2015/06/welcome-to-tranquilpeak-0.4.3-beta/">
```

### Expected behavior

We want `og:url` to be the canonical url, as follows:

```
<meta property="og:url" content="https://tranquilpeak.kakawait.com/2015/06/welcome-to-tranquilpeak-0.4.3-beta/">
```

### Suggested Fix

In [layouts/partials/head](https://github.com/kakawait/hugo-tranquilpeak-theme/blob/master/layouts/partials/head.html), change line 45 from

```
<meta property="og:url" content="{{ .URL }}">
```
to

```
<meta property="og:url" content="{{ .URL | absURL }}">
```

**Comment by kakawait** [comment]
@xiaoyunyang Nice catch. Could you propose a PR with your **suggested fix**?

**Comment by xiaoyunyang** [comment]
@kakawait Sure thing! [PR #270](https://github.com/kakawait/hugo-tranquilpeak-theme/pull/270) created.

**Comment by kakawait** [comment]
@xiaoyunyang I fact was already fixed on previous PR on develop branch

https://github.com/kakawait/hugo-tranquilpeak-theme/pull/239/files#diff-4352d87989c9453b83cdf59856db8b4cR14

Sorry for asking you PR :'(
