### ISSUE TITLE
Statistics

### ISSUE THREAD

**Issue by LinkRober** [kakawait/hugo-tranquilpeak-theme#271]
How to know that how many people visit my page

**Comment by kakawait** [comment]
Nor _Hugo tranquilpeak theme_ nor _Hugo_ itself are able to give you such information because is *static* site generator.

However you can use this theme's _google analytics_ integration to get such information using https://analytics.google.com/analytics/web/

**Comment by kakawait** [comment]
Please consider google analytics integration that could be configured using `config.toml`, see sample

https://github.com/kakawait/hugo-tranquilpeak-theme/blob/580fda488e04028231148ca23ba71a27f86a513d/exampleSite/config.toml#L21
