### ISSUE TITLE
When open sidebar, it will push the content out of the container

### ISSUE THREAD

**Issue by justforuse** [kakawait/hugo-tranquilpeak-theme#278]
### Configuration

 - **Operating system with its version**: 
 - **Browser with its version**:
 - **Hugo version**:  0.42.1
 - **Tranquilpeak version**: 0.4.3-BETA
 - **Do you reproduce on https://tranquilpeak.kakawait.com demo?**: yes
 

### Actual behavior
![qq 20180627010328](https://user-images.githubusercontent.com/11868477/41928301-513434fe-79a7-11e8-8905-fc6c44a24c19.png)

### Steps to reproduce the behavior

It performs well when set `cleanReading: false`

**Comment by johnsoncodehk** [comment]
This problem fixed on my pages, but the animation effect is different, please let me know if the author wants to merge.

Repository: https://github.com/johnsoncodehk/hugo-tranquilpeak-theme
Demo: https://johnsoncodehk.github.io/games/peace-alien/

**Comment by kakawait** [comment]
@johnsoncodehk I'm totally open to your way to do. Feel free to open a PR or give me link a commit or something to see what's diff to apply

**Comment by johnsoncodehk** [comment]
I made these changes: https://github.com/johnsoncodehk/hugo-tranquilpeak-theme/commit/f4d5b32cee6ef3f30aac638ccceaae5b0b4cf08e
If you think this is ok, I will submit a PR.

**Comment by kakawait** [comment]
To be honest I'm not a pro CSS dev so I appreciate some help from community like you just do it now :) Thank you

**Comment by johnsoncodehk** [comment]
I guess you are a designer when I change your code, thank you for this beautiful theme :)

**Comment by johnsoncodehk** [comment]
I updated my branch, the content width is no longer scaled.

Commit: https://github.com/johnsoncodehk/hugo-tranquilpeak-theme/commit/ebff1acf2585d20e9bab1e6220bc21949111854c
![pixel-light](https://user-images.githubusercontent.com/16279759/42576076-3633e222-8554-11e8-9197-9e28c813526c.gif)

**Comment by kakawait** [comment]
@johnsoncodehk that awesome thank I will integrate it
