### ISSUE TITLE
Please Add my blog into the showcase

### ISSUE THREAD

**Issue by jcrincon** [kakawait/hugo-tranquilpeak-theme#279]
Hey, add my blog into the showcase:
[https://www.cruzrincon.com.ve](https://www.cruzrincon.com.ve)
**Dr. Cruz Rincón**
Personal/Profesional Website (in Spanish)

**Static site generator:** [Hugo](https://gohugo.io/)
**Code editor:** [Sublime Text 3](https://www.sublimetext.com/3) + Assorted addons
**Website Hosting, Deploy, CDN & Domain handling:** [Netlify](https://www.netlify.com/)
**Secure Socket Layer:** [Let's Encrypt](https://letsencrypt.org/) (Implemented by Netlify)
**Media CDN:** [Cloudinary](https://cloudinary.com/)
**Code Repository:** [Github](https://www.github.com)
**Boilerplate:** [Victor Hugo](https://github.com/netlify/victor-hugo)
**CMS:** [Forestry](https://forestry.io/)
**Commenting:** [Disqus](https://disqus.com/) --> Planning on a migrating to [Staticman](https://networkhobo.com/2017/12/30/hugo---staticman-nested-replies-and-e-mail-notifications/)
**Customizations:** Multiple changes to Templates & CSS. Fixed malformed Open Graph implementation. Added breadcrumbs to posts using [THIS](https://discourse.gohugo.io/t/implementing-breadcrumb-navigation-in-hugo/1048/9) tip. Added site searching as per [THIS](https://gist.github.com/eddiewebb/735feb48f50f0ddd65ae5606a1cb41ae) developer

**Comment by kakawait** [comment]
@jcrincon Thank for using the theme I will update showcase asap

**Comment by kakawait** [comment]
Added :)
