### ISSUE TITLE
Displaying RSS in Feedly

### ISSUE THREAD

**Issue by jphelps13** [kakawait/hugo-tranquilpeak-theme#286]
Hello, 

I've been searching online for a while now to no avail. Hoping you can help me :) 

I'm using the template theme with R's blogdown package. I've built the site up now and added some content: 

https://jonathan-phelps.netlify.com/

I use feedly to read blogs, and have been trying to get mine in there so that I can review how the content appears to the user, see if it appears in searches etc.

https://feedly.com/i/discover/sources/search/feed/https%3A%2F%2Fjonathan-phelps.netlify.com%2Findex.xml

I'm finding two things:

1. My site won't appear in feedly drop down unless I search the full url above. 
2. When I do click on it, the name of the source is "RSS". For all other sites I follow, they have set the names themselves. Here is a random example I've found where they have set the title:

http://allegralaboratory.net/feed/
Under Source in feedly, it appears as Allegra.

I have one more question.
3. How do I control the description? For some of them they cut of half way through things.

My latest codes are in https://github.com/jphelps13/weblog/tree/tranquil

Thanks for any support, its much appreciated :)

Cheers,
Jonny

**Comment by erblast** [comment]
I dont know about anything about feedly but point three has been adressed in one of the [blogdown issues](https://github.com/rstudio/blogdown/issues/21)

**Comment by kakawait** [comment]
I'll read it carefully. On blogdown issue from @erblast  (thank you) is talking about something we've fixed (about description) but not yet released.

BTW I'll plan to release new version this weekend, I hope it'll fix the thing

**Comment by jphelps13** [comment]
Thank you both :)

**Comment by kakawait** [comment]
I don't think I'm still able to reproduce. Maybe fixed by something recent.
Could you please confirm?
