### ISSUE TITLE
please consider adding my blog to your showcases

### ISSUE THREAD

**Issue by erblast** [kakawait/hugo-tranquilpeak-theme#300]
Hi,

thank you for creating this great template. I would be honored if you would add my blog to your showcases. [https://www.datisticsblog.com](https://www.datisticsblog.com)
Cheers 

Björn

**Comment by kakawait** [comment]
Just added to https://tranquilpeak.kakawait.com/2015/06/who-is-using-tranquilpeak-hugo-theme/

**Comment by erblast** [comment]
thanks a lot,  and also for the new version
