### ISSUE TITLE
Where to edit sidebar components such as: particular element font size or the menu.links object icon

### ISSUE THREAD

**Issue by konradsemsch** [kakawait/hugo-tranquilpeak-theme#304]
Font size - should I somehow add css code to a particular element to modify it?

Menu.links elements - how to submit a different picture to replace the default "sidebar-button-icon fa fa-lg fa-category" below?

[[menu.links]]
  weight = 1
  identifier = "cv"
  name = "CV"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-category\"></i>"
  url = "/cv"

**Comment by konradsemsch** [comment]
Ok, solved the second one when I found a list of possibile elements e.g.: [here](https://www.w3schools.com/w3css/w3css_icons.asp).

However, I'm still not quite sure how to modify menu font size - could anyone help out?

**Comment by erblast** [comment]
i was actuallly trying the same thing then found this [issue](https://github.com/kakawait/hugo-tranquilpeak-theme/issues/259) and decided that it was to complicated to try. Apperantly something with npm and compiling scss. Whatever that means. It would be great if we could simply change font parameters (for my use case mostly color, to get better contrast for different background images)

**Comment by kakawait** [comment]
I think there is enough options for the theme.
I still prefer working on simplifying the path to customize the theme (by multiple factor like #480 or improve dev doc)

I'll close it in flavor of #480
