### ISSUE TITLE
cover image relative path does not display in post

### ISSUE THREAD

**Issue by erblast** [kakawait/hugo-tranquilpeak-theme#305]
**hugo-tranquilpeak-them 0.4.3**
**hugo v0.46 darwin/amd64**

If I take your example site and add a new post with the following yaml parameters

```
---
title: "Cover Image relative path"
date: "2018-09-27"
slug: "cover_image_relative"
coverImage: img/showcase.png
---
```

and another one like this

```
---
title: "Cover Image url path"
date: "2018-09-26"
slug: "cover_image_url"
coverImage: https://github.com/kakawait/hugo-tranquilpeak-theme/raw/master/showcase.png
---
```

I will see both cover images on the landing page but only the post with the url path will show the cover image while the post with the relative path will default to the cover image when I click on it. 

Is this a bug or intended behaviour, is there a way around it without resorting to the url path?

**great theme by the way I am using it now for a second project at work and will keep using it for my own blog.**

**Comment by kakawait** [comment]
@erblast Thank for reporting.

For the first scenario, if you replace with `coverImage: /img/showcase.png` does it do what you would like to see ?

**Comment by erblast** [comment]
this actually does the trick, however the problem persists if I add another level to my baseURL in `config.toml`

```
baseURL = "https://example.org/dira/"
````

**Comment by xenlo** [comment]
I get the same issue. If I add a sub folder in my baseURL, it the references to the CSS and images goes wrong.

### Versions
- hugo-tranquilpeak-theme 0.4.4-BETA
- hugo v0.37.1 linux/amd64
