### ISSUE TITLE
Add my blog into the showcase

### ISSUE THREAD

**Issue by fu-sen** [kakawait/hugo-tranquilpeak-theme#307]
Hi, My blog adopted this theme. I want you to add it to the showcase:

- URL: https://balloon.gq/
- Name: BALLOON a.k.a. Fu-sen. (Japanese: ふうせん🎈 Fu-sen.)

**Comment by kakawait** [comment]
Just added to https://tranquilpeak.kakawait.com/2015/06/who-is-using-tranquilpeak-hugo-theme/

**Comment by fu-sen** [comment]
I confirmed that. This theme is my favorite.
