### ISSUE TITLE
Add my blog into the showcase

### ISSUE THREAD

**Issue by IrvanFza** [kakawait/hugo-tranquilpeak-theme#308]
Hey, I just set up my blog with Hugo and use your awesome theme. Really love your work! Please add my blog into the showcase:

URL: [https://irvan.co](https://irvan.co)
Name: Irvan's Blog

P.S.: There are no any posts at the moment. Some of the pages also still work in progress. :)

**Comment by kakawait** [comment]
Url seems to be KO
