### ISSUE TITLE
How can I change the color of the text and favicons in the sidebar menu?

### ISSUE THREAD

**Issue by everetr** [kakawait/hugo-tranquilpeak-theme#312]
### Question

How can I change the color of the text and favicons in the sidebar menu? I think white text blends in too well with the default background photo, as well as the background photo I chose to replace it with. See here:

![image](https://user-images.githubusercontent.com/9023041/48307959-8bb1bf80-e526-11e8-9398-3b24805a6d5c.png)

### Configuration

 - **OS**: Ubuntu 18.04.1 LTS Bionic Beaver
 - **Browser:** Firefox for Ubuntu 63.0 (64-bit)
 - **Hugo version**: 0.51
 - **Tranquilpeak version**: 0.4.4-BETA
 - **Do you reproduce on https://tranquilpeak.kakawait.com demo?**: Not relevant, I think.

**Comment by fu-sen** [comment]
This seems to be fixed at the theme level.

My blog ( https://fu-sen.surge.sh/ ) is changing text colors using custom CSS.

**config.toml**
```
  [[params.customCSS]]
     href = "css/mystyle.css"
```

**static/css/mystyle.css**
```
#sidebar .sidebar-profile .sidebar-profile-name
{
    color: #252525;
}
#sidebar ul.sidebar-buttons li.sidebar-button .sidebar-button-link
{
    color: #252525;
}
@media only screen and (min-width: 1280px)
{
  #sidebar[data-behavior="1"] .sidebar-profile .sidebar-profile-bio,
  #sidebar[data-behavior="1"] .sidebar-profile .sidebar-profile-job,
  #sidebar[data-behavior="1"] .sidebar-profile .sidebar-profile-location 
  {
    color: #252525;
  }
}
```

Perhaps you have to add more.

I thought that the option to change the font color may exist in the theme.

![2018-12-03 21 56 47](https://user-images.githubusercontent.com/5434159/49375087-a69eda80-f746-11e8-939a-9d85d3ae4d14.jpg)

**Comment by fu-sen** [comment]
About Favicon, 
Does it show the image to the left of the text?

This uses [Font Awesome](https://fontawesome.com/icons).
Please pay attention to the description of **fa-iconname**.

**config.toml**
```
[[menu.main]]
  weight = 1
  identifier = "home"
  name = "Home"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-home\"></i>"
  url = "/"
```

```
  [[params.sharingOptions]]
    name = "Facebook"
    icon = "fa-facebook-official"
    url = "https://www.facebook.com/sharer/sharer.php?u=%s"
```

**Comment by everetr** [comment]
This worked. Thank you very much! I really appreciate the detailed answers you gave.

Note to anyone reading this: fu-sen's first comment fixed both my text and favicon color issues.

**Comment by vidyasagarbhargava** [comment]
On hovering the color changes to white how to keep it black?

**Comment by fu-sen** [comment]
@vidyasagarbhargava 
> On hovering the color changes to white how to keep it black?

It has no change in appearance and is not recommended. This is a little red:
```
#sidebar ul.sidebar-buttons li.sidebar-button .sidebar-button-link:hover
{
    color: #880000;
}
```
