### ISSUE TITLE
not overwrite window.onload

### ISSUE THREAD

**Issue by dongzhuoer** [kakawait/hugo-tranquilpeak-theme#313]
in `layouts/partials/script.html`, you write

```js
window.onload = updateMinWidth;
```

But I use `pagedtable.js` in `<head>`, which includes

```js
window.onload = function() {
  PagedTableDoc.initAll();
};
```

Then **PagedTable** can't function properly.

Would you mind use 

```js
function addOnload(fun){
    var last = window.onload;
    window.onload = function(){
        if(last) last();
        fun();
    }
} 
addOnload(updateMinWidth);
```

**Comment by kakawait** [comment]
@dongzhuoer btw I don't remember why I did that. With or without this piece of code it works same way. I may remove it completely on next release
