### ISSUE TITLE
R code lines display in disorder when using blogdown

### ISSUE THREAD

**Issue by JiaxiangBU** [kakawait/hugo-tranquilpeak-theme#314]
### Configuration

 - **Operating system with its version**: macOS  10.14
 - **Browser with its version**: Chrome latest version
 - **Hugo version**:  0.46
 - **Tranquilpeak version**: 0.4.4-BETA
 - **Do you reproduce on https://tranquilpeak.kakawait.com demo?**:
 

### Actual behavior

I use R package `blogdown` to produce the blog site. But I find the R code line is in the disorder.
Here is 
![image](https://user-images.githubusercontent.com/15884785/48663053-87a51500-eac5-11e8-9a60-9e2306950f72.png)

Here is my code.

```
some_mtr <- matrix(c(3,0,0,2),nrow = 2,byrow = T)
some_mtr
```

**Comment by tcgriffith** [comment]
I was gonna file an issue like this one.
Related issues from blogdown:

https://github.com/rstudio/blogdown/issues/321

https://github.com/rstudio/blogdown/issues/345

**Comment by kakawait** [comment]
Just add note for myself https://github.com/rstudio/blogdown/issues/321#issuecomment-409075782

**Comment by kakawait** [comment]
On latest release `0.5.0-BETA` Highlight.js was updated. Can you please confirm is still an issue?
