### ISSUE TITLE
Cover image is shown while scrolling the post article

### ISSUE THREAD

**Issue by rglsk** [kakawait/hugo-tranquilpeak-theme#319]
Please help :) I noticed it when I used this cool thema on my blog. It also happen on demo site.

### Configuration

 - **Operating system with its version**: macOS High Sierra, v10.13.5
 - **Browser with its version**: Chrome, Version 71.0.3578.98 (Official Build) (64-bit)
 - **Hugo version**:  v0.50/extended darwin/amd64 BuildDate: unknown
 - **Tranquilpeak version**:"version": "0.4.4-BETA",
 - **Do you reproduce on https://tranquilpeak.kakawait.com demo?**: yes
 

While scrolling articles cover/background image is blinking sometimes at the bottom. 
This is happening on many systems and browsers as far as I have seen.

While scrolling cover image should not blink at the bottom

1. Go to https://tranquilpeak.kakawait.com/2015/06/who-is-using-tranquilpeak-hugo-theme/
2. Scroll down (can be rapid) 
3. If not happen refresh and try again

**Comment by kakawait** [comment]
@Piotr-Rogulski sorry but I tried many thing but I'm not able to reproduce (or maybe I missunderstand)

Do you have video or something that can help me to understand?
