### ISSUE TITLE
problem on small screen

### ISSUE THREAD

**Issue by jeshs** [kakawait/hugo-tranquilpeak-theme#322]
### Configuration

 - **Operating system with its version**: 
 - **Browser with its version**:firefox nightly
 - **Hugo version**: 0.53
 - **Tranquilpeak version**: 0.44-BETA
 - **Do you reproduce on https://tranquilpeak.kakawait.com demo?**:yes
 

### Actual behavior
1、The lower left corner of the graphic (previous and next)shows the split
2、There is a share button in the lower right corner of the small screen, which is not displayed on the big screen.
[screenshot](https://i.loli.net/2019/01/20/5c43e7ee9c5ac.png)

### Expected behavior
1、correct display
2、don't display share button

### Steps to reproduce the behavior

**Comment by kakawait** [comment]
I was able to reproduce thank for reporting

**Comment by kakawait** [comment]
Seems to affect only FF (not Chrome)
