### ISSUE TITLE
deploy site error netlify

### ISSUE THREAD

**Issue by nodoambiental** [kakawait/hugo-tranquilpeak-theme#328]
I trying deploy a webpage with tranquilpeak theme. I have two successful previous attempts. However, I can not find now how is the error, after a day o new attempts. 
I test several hugo versions (0.44, 0.35, 0.30), but doesn't work.
When I trigger deploy in netlify, I get the following outcome. I changed some partials but I can not see the fail.

12:38:48 PM: Started building sites ...
12:38:48 PM: ERROR 2019/02/16 15:38:48 Error while rendering "page": template: theme/_default/single.html:1:3: executing "theme/_default/single.html" at <partial "head.html" ...>: error calling partial: template: theme/partials/head.html:28:7: executing "theme/partials/head.html" at <partial "head_start....>: error calling partial: Partial "head_start.html" not found
12:38:48 PM: Caching artifacts
12:38:48 PM: Started saving node modules
12:38:48 PM: Finished saving node modules
12:38:48 PM: Started saving pip cache
12:38:48 PM: Finished saving pip cache
12:38:48 PM: Started saving emacs cask dependencies
12:38:48 PM: Finished saving emacs cask dependencies
12:38:48 PM: Started saving maven dependencies
12:38:48 PM: Finished saving maven dependencies
12:38:48 PM: Started saving boot dependencies
12:38:49 PM: Finished saving boot dependencies
12:38:49 PM: Started saving go dependencies
12:38:49 PM: Finished saving go dependencies
12:38:49 PM: Cached node version v8.15.0
12:38:49 PM: Error running command: Build script returned non-zero exit code: 255
12:38:49 PM: Failing build: Failed to build site
12:38:49 PM: failed during stage 'building site': Build script returned non-zero exit code: 255
12:38:49 PM: Finished processing build request in 15.983823797s
12:38:49 PM: Shutting down logging, 0 messages pending

**Comment by xenlo** [comment]
Hi @nodoambiental,

So the error message tells you that the file `Partial "head_start.html" not found`. And I found a commit in you repo that you actually deleted that file: 
- https://github.com/nodoambiental/portal-tranquilpeak/commit/a5433e477addae10295b3eaedb4eac0729880eac

As you can see in the original repo, this file is present even if empty:
- https://github.com/kakawait/hugo-tranquilpeak-theme/blob/master/layouts/partials/head_start.html

Can you try to recreate that file and see if it still complains? 
```
touch themes/hugo-tranquilpeak-theme/layouts/partials/head_start.html
```

**Comment by nodoambiental** [comment]
Hi @xenlo,
Thank you very much. I add an empty file "head_start.html" in layouts/partials folders, creating it by "Create new file" within the repository. Then, new errors were present. Finally, adding also the empty files "head_end.html", "foot_start.html", and "foot_end.html", the deploy was successful. I used Hugo version 0.44 as build environment in Netlify. Thanks! @maordano

Deploy details from Netlify:
1:43:29 PM: Building sites …
1:43:29 PM: 
1:43:29 PM:                    | ES-ES
1:43:29 PM: +------------------+-------+
1:43:29 PM:   Pages            |    98
1:43:29 PM:   Paginator pages  |     0
1:43:29 PM:   Non-page files   |     1
1:43:29 PM:   Static files     |    26
1:43:29 PM:   Processed images
1:43:29 PM: |     0
1:43:29 PM:   Aliases          |    42
1:43:29 PM:   Sitemaps
1:43:29 PM: |     1
1:43:29 PM:   Cleaned          |     0
1:43:29 PM: Total in 223 ms
1:43:29 PM: Caching artifacts
1:43:29 PM: Started saving node modules
1:43:29 PM: Finished saving node modules
1:43:29 PM: Started saving pip cache
1:43:29 PM: Finished saving pip cache
1:43:29 PM: Started saving emacs cask dependencies
1:43:29 PM: Finished saving emacs cask dependencies
1:43:29 PM: Started saving maven dependencies
1:43:29 PM: Finished saving maven dependencies
1:43:29 PM: Started saving boot dependencies
1:43:29 PM: Finished saving boot dependencies
1:43:29 PM: Started saving go dependencies
1:43:29 PM: Finished saving go dependencies
1:43:29 PM: Build script success
1:43:29 PM: Starting to deploy site from 'public'
1:43:32 PM: Starting post processing
1:43:33 PM: Post processing done
1:43:33 PM: Site is live
1:43:38 PM: Finished processing build request in 17.320169118s
1:43:38 PM: Shutting down logging, 0 messages pending
