### ISSUE TITLE
Multilingual option in the blog post?

### ISSUE THREAD

**Issue by vitoranunciato** [kakawait/hugo-tranquilpeak-theme#335]
It's possible to insert a multilingual function only in the blog post?
Something like: "I open a new post and I can select if I want to read that post in EN or FR..."
If anyone already does that thing can help me?
Thx friends...

**Comment by kakawait** [comment]
@vitoranunciato you should start with https://gohugo.io/content-management/multilingual/

to be honest I never try multilingual feature from Hugo so maybe could have bug with current theme. But feel free to give feedback.

Mostly multilang thing is related to Hugo itself and not theme, theme could only translate itself but for content/post is Hugo related

**Comment by denmasgie** [comment]
You must add your language to the theme / tranquilpeak / i18n folder

And add your language in the form .yaml For example: id-id.yaml 

For the Indonesian language that I use on the blog.It's work for me
