### ISSUE TITLE
blog posts can only see in "tags" page

### ISSUE THREAD

**Issue by shuzang** [kakawait/hugo-tranquilpeak-theme#367]
I like this theme. And when I finished everything, I found I can't see my blog posts in home, categories and archives pages, bug I can see in tags page. It's relly weird. And I don't know why. The picture followed.

![categories](https://user-images.githubusercontent.com/26682846/62683076-35f44000-b9f0-11e9-9cd3-e25751cbc79c.png)
![home](https://user-images.githubusercontent.com/26682846/62683078-368cd680-b9f0-11e9-9a90-7db8efdea65a.png)
![tags](https://user-images.githubusercontent.com/26682846/62683080-37256d00-b9f0-11e9-915e-e4965dc6ecfb.png)

**Comment by kakawait** [comment]
@shuzang could you please try adding `type: post` inside each post markdown?

**Comment by shuzang** [comment]
Thanks, I have found the reason. That's because the previous theme I used set the directory name to "content/posts", and I have not change the folder name to "post".
