### ISSUE TITLE
Hugo 0.57.0 shows only Posts on the homepage

### ISSUE THREAD

**Issue by fu-sen** [kakawait/hugo-tranquilpeak-theme#371]
Hugo 0.57.0 has been released. If this is used, the home page is "Posts" only:
 
![スクリーンショット 2019-08-14 20 38 19](https://user-images.githubusercontent.com/5434159/63018627-474bb980-bed4-11e9-91b5-30e6ca54f5ec.jpg)

This has something to do with Hugo 0.57.0 spec change, but it may be temporary due to a bug in Hugo.
Hugo 0.56.3 lists correctly. This is a temporary workaround.

**Comment by kakawait** [comment]
Thank for reporting. Currently I'm in vacancies so I'll not be able to do something before 2 weeks. I strongly recommend you to downgrade Hugo until i find a fix

**Comment by fu-sen** [comment]
I can edit the theme file to some extent. The measures in the above issue work well.
This could be a (temporary) solution.
However, this has an impact on several themes and will require discussion of this issue for some time.

**Comment by fu-sen** [comment]
Thank you. I immediately reflected my blog https://balloon.gq/ , It works in the way we expect.
```
<meta name="generator" content="Hugo 0.57.0 with theme Tranquilpeak 0.4.7-BETA">
```

**Comment by kakawait** [comment]
Glad to help. Same for https://tranquilpeak.kakawait.com just updated with `0.57.0` and `0.4.7-BETA`

**Comment by jhchou** [comment]
Has this bug recurred? I just updated Hugo to v0.69.2 and re-installed tranquilpeak, and I'm having the home page showing only Posts.

I double-checked and my `/layouts/index.html` does contain the updated:

```
{{ $paginator := .Paginate (where .Site.RegularPages "Type" "post") }}
```

**Comment by kakawait** [comment]
@jhchou I'll on monday. I don't have enough stuff atm to check more.
But if you could test previous release (0.68.x) it will help me. If it's working on 0.68.x please open a new ticket I'll fix it asap (with dedicated release)

**Comment by jhchou** [comment]
Thanks much — love that you still maintain the tranquilpeak theme.

• updated Hugo from 0.56.3 to 0.68.3 and the homepage bug recurred.
• I uninstalled Hugo again and re-installed 0.56.3 and the homepage is working again

So I am seeing the homepage bug with Hugo versions 0.68.3 and 0.69.2, but not with 0.56.3. No idea why.

Just in case it’s relevant to you (I’m not that knowledgable about how this all works), I’m running:
• Mac OS X 10.14.5
• building the blog from within R / RStudio, using the blogdown package

**Comment by fu-sen** [comment]
@jhchou It was a Hugo spec change, and the theme had to be reflected.
Follow what happened with @kakawait 's action on this page.

**Comment by kakawait** [comment]
> @jhchou It was a Hugo spec change, and the theme had to be reflected.
> Follow what happened with @kakawait 's action on this page.

But I tough what I delivered for 0.4.7 fixes the problem.

@fu-sen you have the same issue?

**Comment by kakawait** [comment]
@jhchou your "post" folder is "posts" or "post"?

**Comment by jhchou** [comment]
The markdown source for the pages (for R / RStudio with the blogdown package) is at:  <toplevel> / content / post /

**Comment by fu-sen** [comment]
No. If it's recurring, I'll New issue. My blog is fine.

**Comment by fu-sen** [comment]
@kakawait No. I cloned the latest theme, but I'm blogging fine.
This looks like a @jhchou personal issue.

**Comment by kakawait** [comment]
@jhchou As same as @fu-sen I don't have any issue.
Do you have any sample? Could you please upload your src project and with builded folder? (because i'm not expert of R/Blogdown, I may use directly builded version)
