### ISSUE TITLE
Change about design

### ISSUE THREAD

**Issue by stephanbisser** [kakawait/hugo-tranquilpeak-theme#377]
Hi, I wanted to change the appearance of the about page.
I inserted an attribute in my toml called "description" in the author section and referenced this in my about.html (which works fine:)
`{{ with .Site.Author.description }}
      <br/>
      <div id="about-card-description" class="about-card-description">{{ . | markdownify }}</div>
    {{ end }}`

However, the text is being rendered odd although it should get the same CSS settings as bio or job for example from the _about.scss:

![image](https://user-images.githubusercontent.com/29750798/63727967-65190700-c862-11e9-8219-4f7522dd9420.png)

could you please assist me?

**Comment by kakawait** [comment]
> the text is being rendered odd

What do you exactly mean by that?

I mean I could help you but please describe me what you would like at final result
