### ISSUE TITLE
Potential security vulnerabilities found in the eslint-utils and lodash dependencies

### ISSUE THREAD

**Issue by everettttt** [kakawait/hugo-tranquilpeak-theme#380]
I received these security alerts today:

![image](https://user-images.githubusercontent.com/9023041/64831200-8e47d000-d5a2-11e9-9c39-7f313caea033.png)

![image](https://user-images.githubusercontent.com/9023041/64831211-9c95ec00-d5a2-11e9-89f8-b1918240316f.png)

[package-lock.json](https://github.com/kakawait/hugo-tranquilpeak-theme/blob/master/package-lock.json) needs updating.

**Comment by kakawait** [comment]
@everetr Yes I was working on it, currently many of deps already upgraded on https://github.com/kakawait/hugo-tranquilpeak-theme/pull/356 branch, that will be part of next release

**Comment by rugk** [comment]
Likely also fixed in https://github.com/kakawait/hugo-tranquilpeak-theme/pull/435

**Comment by kakawait** [comment]
fixed by #472
