### ISSUE TITLE
Add my blog into the showcase

### ISSUE THREAD

**Issue by avra911** [kakawait/hugo-tranquilpeak-theme#381]
Hey, please add my blog into the showcase: https://www.avramescu.net.
A big thank you, @kakawait !

Kind regards,
Razvan

**Comment by kakawait** [comment]
I really love your bio 

> I am a father, a husband, a developer and occasionally cyclist.

perfectly fit with myself itoo :)

**Comment by avra911** [comment]
> I really love your bio
> 
> > I am a father, a husband, a developer and occasionally cyclist.
> 
> perfectly fit with myself itoo :)

I see that you highlighted the bio in the screenshot. Appreciate it!

Thank you for the awesome theme!
