### ISSUE TITLE
Update font-awesome icons to version 5

### ISSUE THREAD

**Issue by venturarome** [kakawait/hugo-tranquilpeak-theme#382]
This is just a request if maintainers consider it. Font-awesome icons' last version is 5.11.2, but currently, the template is using an older version, which is lacking many new icons. For instance, icon fa-facebook-messenger is not available.
Here PR: [click](https://github.com/kakawait/hugo-tranquilpeak-theme/pull/383)

**Comment by mayuso** [comment]
I am trying to add Itch.io's icon and the current version doesn't contain it. It's 5.8+.

Would be nice to have

**Comment by kakawait** [comment]
fixed by #356
