### ISSUE TITLE
http security issue and its solution 

### ISSUE THREAD

**Issue by physhik** [kakawait/hugo-tranquilpeak-theme#387]
### Configuration

 - **Operating system with its version**: MacOS Mojave
 - **Browser with its version**: firefox version 70
 - **Hugo version**: 0.59
 - **Tranquilpeak version**: 0.4.4 beta You can find version on package.json -->
 - **Do you reproduce on https://tranquilpeak.kakawait.com demo?**: yes
 

### Actual behavior

There's security trouble on firefox, chrome when your posts or any other content include "http" link. Especially when you use firefox, the webpage breaks down. 

### Solution 

I resolved this trouble by doing one of the next 4 

changing 
1) http into https 

2) http://www  into   //www

3) http://www into //

4) Test links at your localhost and find working link 

### Another issue and a solution

When you use your own domain, avoid using http domain. Use https

**Comment by kakawait** [comment]
@physhik do you mean _http_ resources including inside theme or your _http_ resources?

Do you change anything inside the theme that I could report?
