### ISSUE TITLE
Modify my blog into the showcase

### ISSUE THREAD

**Issue by fu-sen** [kakawait/hugo-tranquilpeak-theme#389]
My blog is already listed, but I want to change it.
https://github.com/kakawait/hugo-tranquilpeak-theme/issues/307

Name:
Current: BALLOON a.k.a. Fu-sen
Change: 🎈 BALLOON | FU-SEN (You can also remove 🎈)

URL: (I needed to change because there was a bug in SNS)
Current: https : //balloon.gq/
Change: https://balloon.asia/

In addition, this top page has a Cover image. If you want to screen capture the image again, this blog list may be ideal:
https://balloon.asia/post/

**Comment by kakawait** [comment]
@fu-sen thank for keeping your showcase up to date. I appreciate.

I'll update that asap

**Comment by fu-sen** [comment]
Oh, I'm sorry. I recently changed my English name. (The Japanese name has also changed)
I edited the original request

**Comment by fu-sen** [comment]
I will comment again and notify you. I have integrated other webs into this theme that I originally used as a blog.
Because this theme was really great 👍 This domain has been further modified in consideration of SEO.

**Comment by kakawait** [comment]
Yes I have to integrate dev to master. I'll try next week

**Comment by fu-sen** [comment]
Oh, you overlooked it.
I am currently moving from `https://blog.balloon.im/` to https://balloon.asia/ .
I am modifying the original text, but you do not reflect it.

**Comment by kakawait** [comment]
Yes I think I've added to showcase long time ago and I didn't check your edit. I'll fix it asap

**Comment by fu-sen** [comment]
I confirmed the reflection. thank you!
