### ISSUE TITLE
why no TOC

### ISSUE THREAD

**Issue by YHYJ** [kakawait/hugo-tranquilpeak-theme#395]
### Configuration

> i use [travis-ci](https://travis-ci.org/), but also no TOC to run `hugo server -D -w`

 - **Operating system with its version**: Arch Linux x86_64
 - **Browser with its version**:Chromium 78.0.3904.108 & Firefox 70.0.1
 - **Hugo version**: Hugo Static Site Generator v0.60.1/extended linux/amd64 BuildDate: unknown
 - **Tranquilpeak version**: 0.4.7-BETA
 - **Do you reproduce on https://tranquilpeak.kakawait.com demo?**:yes
 

### Actual behavior
no TOC

### Expected behavior
add `<!-- toc -->`and then I can see the TOC

### Steps to reproduce the behavior
i dont know, i did nothing

**Comment by kakawait** [comment]
@YHYJ thank for reporting. I confirm `<!-- toc -->` does not work since `0.60`

I strongly suspect comes from new Markdown lib `CommonMark` (before Hugo was using `BlackFriday`)

Currently I don't have workaround

**Comment by kakawait** [comment]
You could try two workaround:

1. Enable `unsafe` https://gohugo.io/getting-started/configuration-markup/#goldmark

inside `config.toml`

```toml
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
```

it works

2. Or force using `BlackFriday`

**Comment by YHYJ** [comment]
i'm sure workaround 1 is invalid, it just shows ‘Table of Contents’ but no content, workaround 2 is effective

**Comment by gy0624ww** [comment]
@YHYJ HI  how to force to use BlackFriday?

**Comment by YHYJ** [comment]
Force use [BlackFriday](https://gohugo.io/getting-started/configuration-markup/#blackfriday)
like this:
![blackfriday](https://user-images.githubusercontent.com/21995281/71948627-94c21d80-320b-11ea-8361-0a8b68f97e11.png)

**Comment by gy0624ww** [comment]
> Force use [BlackFriday](https://gohugo.io/getting-started/configuration-markup/#blackfriday)
> like this:
> ![blackfriday](https://user-images.githubusercontent.com/21995281/71948627-94c21d80-320b-11ea-8361-0a8b68f97e11.png)

thanks

**Comment by goldjg** [comment]
> i'm sure workaround 1 is invalid, it just shows ‘Table of Contents’ but no content, workaround 2 is effective

Unsafe worked for me.
![43DEE0D3-1182-4191-8541-24802036EEE0](https://user-images.githubusercontent.com/43296126/72224451-a93b4880-3572-11ea-9c1d-906879c8446b.jpeg)

**Comment by kakawait** [comment]
I'll create new `shortcodes` for TOC that will support _Goldmark_ parser.

I can't rely on html comment anymore because _Goldmark_ remove it (except if you enable `unsafe`)
