### ISSUE TITLE
Table of Contents broken in Hugo 0.60.0 and above

### ISSUE THREAD

**Issue by goldjg** [kakawait/hugo-tranquilpeak-theme#400]
### Configuration 

 - **Operating system**: 13.3
 - **Browser**: Safari
 - **Hugo version:**: 0.62.1
 - **Tranquilpeak version**: 0.4.7-beta
 - **Do you reproduce on https://tranquilpeak.kakawait.com demo?**: No
 

### Actual behavior
With '<!— toc —>' in the markdown, no table of contents is displayed if using Hugo 0.60.0 or higher.

### Expected behavior
 Table of Contents displayed

### Steps to reproduce the behavior
Add '<!— toc —>' to a markdown page with headings (#, ## etc) in the content and build the site with Hugo 0.60.0 or higher

**Comment by tlex** [comment]
Seems to be the same as #395

**Comment by goldjg** [comment]
> Seems to be the same as #395

Yes - I didn’t get from the title of #395 that it was  TOC issue - title working needs to be clearer

**Comment by kakawait** [comment]
Yes related to new parser that remove comment.

I have to find a long term solution for instance please use workaround from #349 

I'll close it in flavor of #395
