### ISSUE TITLE
Date is not formatted correctly

### ISSUE THREAD

**Issue by fallenwood** [kakawait/hugo-tranquilpeak-theme#402]
### Configuration

 - **Operating system with its version**: Windows 10 1909 Enterprise
 - **Browser with its version**: Microsoft Edge 79.0.309.68
 - **Hugo version**:  0.62.0/extended
 - **Tranquilpeak version**:  master/0.4.7-BETA
 - **Do you reproduce on https://tranquilpeak.kakawait.com demo?**: no
 

### Actual behavior
With `dateFormat = "2 January 2006"` in `[params]`

The date is formatted to
```
<time itemprop="datePublished" datetime="2020-01-20T10:20:14+08:00">
        
  
  
  
  
    20  2020
  

      </time>
```

### Expected behavior
It should be something like `20 January 2020`

### Steps to reproduce the behavior
`hugo new post/hello.md`

`hugo serve`

**Comment by matcha440** [comment]
I recently noticed this behavior, too.  Even the default format doesn't show correctly.  I did notice, however, that the abbreviated month does work (for example `2 Jan 2006`).  So something funky with the underlying date formatting function in go is my suspicion.

For reference, I'm using hugo version `Hugo Static Site Generator v0.74.3-DA0437B4/extended linux/amd64 BuildDate: 2020-07-23T16:30:30Z`

**Comment by kakawait** [comment]
With `dateFormat = "2 January 2006"` in `[params]`

<img width="859" alt="Screen Shot 2021-09-08 at 11 11 01" src="https://user-images.githubusercontent.com/275609/132481327-c0f62703-f79b-4f57-b06d-e8a8d325f5da.png">

I'm not able to reproduce

<img width="851" alt="Screen Shot 2021-09-08 at 11 11 22" src="https://user-images.githubusercontent.com/275609/132481384-14ce9c78-294f-4040-a4b0-c00cad3f11ca.png">

Do you have more information.

@matcha440 even with `2 Jan 2006` I don't have any issue

**Comment by matcha440** [comment]
I'm wondering if there isn't some sort of customization on my site somewhere that is throwing things off.  I updated both my version of hugo and this theme to the latest and still see the issue.  I'll try seeing if I can isolate this to a copy I can share with you later for further troubleshooting.

**Comment by matcha440** [comment]
@kakawait it appears the issue I was running into had something to do with my `config.toml` file, which was based on an older version.  Recreating using a copy from  the current version of the example site causes this to go away.  I still don't know exactly what it was that was throwing it off, but I think I at least have a solution.  Thanks.

**Comment by kakawait** [comment]
Or maybe white or invisible chars. Idk but glad to know is working now

**Comment by kakawait** [comment]
Or maybe white or invisible chars. Idk but glad to know is working now

**Comment by fallenwood** [comment]
I cannot recall the details of this issue, but if it is resolved, I can close it.

**Comment by ghost** [comment]
I just had this same issue. Solution was to add `defaultContentLanguage = "en-us"` to my config file.
