### ISSUE TITLE
R code highlighting

### ISSUE THREAD

**Issue by adrianBandolon** [kakawait/hugo-tranquilpeak-theme#405]
### Configuration

 - **Operating system with its version** Ubuntu 18.04.4 LTS: 
 - **Browser with its version** Google Chrome Version 80.0.3987.87 (Official Build) (64-bit):
 - **Hugo version**: Hugo Static Site Generator v0.64.0-241DB8F7/extended linux/amd64 BuildDate: 2020-02-04T09:14:57Z
 - **Tranquilpeak version**: 0.4.7-BETA
 - **Do you reproduce on https://tranquilpeak.kakawait.com demo?**:
 

### Actual behavior
Code highlighting for R is not a supported language for highlight.js implementation in tranquilpeak theme.

### Expected behavior
Would like to request that R be supported in the highlight.js implementation in tranquilpeak theme

### Steps to reproduce the behavior

**Comment by kakawait** [comment]
Do you try with configuration similar to https://github.com/kakawait/hugo-tranquilpeak-theme/issues/186#issuecomment-346593802

You could find `r.js` info here https://cdnjs.com/libraries/highlight.js/
