### ISSUE TITLE
Problem with TOC

### ISSUE THREAD

**Issue by inspire-lts** [kakawait/hugo-tranquilpeak-theme#407]
### Configuration

 - **Operating system with its version**: Windows10
 - **Browser with its version**: Google Chrome
 - **Hugo version**: Hugo Static Site Generator v0.62.1-A1518704 windows/amd64 BuildDate: 2020-01-01T17:39:35Z
 - **Tranquilpeak version**: 0.4.7-BETA
 

### Actual behavior
I use <!-- toc --!> in the post content, but didn't get table of contents. Then use the same **config.toml** in other computer, but it  work.  So how can i get correct table of contents.
thank you!

**Comment by inspire-lts** [comment]
I know! My hugo version is Incompatible with tranquilpeak version. So down hugo version， it can work.

**Comment by kakawait** [comment]
@inspire-lts instead you can do workaround describe here

https://github.com/kakawait/hugo-tranquilpeak-theme/issues/395

And let you use latest Hugo Version
