### ISSUE TITLE
Tabbed-code-block can't work.

### ISSUE THREAD

**Issue by SAquarius** [kakawait/hugo-tranquilpeak-theme#412]
### Configuration

 - **Window 10**: 
 - **Microsoft Edge(Chromium) 81.0.416.45**:
 - **Hugo version: 0.55.6**: 
 - **Tranquilpeak version: 0.4.7**:
 
I want to use Tabbed code block and I really use the format in the User documentation.
However, there is nothing showed on my posts.
By the way, I have tested different hugo version, such as 0.57.2 and 0.68.0, but both didn't work as expected.

**Comment by kakawait** [comment]
Could you please past your .md content in order to test on my side. Because currently no issue with tabbed-code-block
