### ISSUE TITLE
Add my blog into the showcase

### ISSUE THREAD

**Issue by orrymr** [kakawait/hugo-tranquilpeak-theme#415]
Hey, add my blog into the showcase:

http://www.orrymr.com/

Awesome theme :)

**Comment by kakawait** [comment]
Thank you, I'll add it next drop

**Comment by kakawait** [comment]
Link seems to be broken now?

**Comment by orrymr** [comment]
> Link seems to be broken now?

Sorry, completely forgot to reply.

Yeah, I've taken the blog down.
