### ISSUE TITLE
Is there a way to adjust the sidebar profile picture size?

### ISSUE THREAD

**Issue by jjasser** [kakawait/hugo-tranquilpeak-theme#417]
Hello! I have my images stored in my local "images" directory, and I can see my profile picture successfully. When I run Hugo Serve, it shows my profile picture being 90px by 90px. Is there a way to adjust that to 180px by 180px? The original picture size is 570px by 760px. Thank you!

**Comment by kakawait** [comment]
Without overriding the theme css (https://github.com/kakawait/hugo-tranquilpeak-theme/blob/master/src/scss/utils/mixins/_sidebar.scss) is not possible. Values are hardcoded

**Comment by yakav** [comment]
Thank you Kakawait!

**Comment by kakawait** [comment]
I'll close issue. Seems to be ok for you. If not please re-open
