### ISSUE TITLE
open and closing of sidebar

### ISSUE THREAD

**Issue by ourmaninindia** [kakawait/hugo-tranquilpeak-theme#418]
Hi

Is there anything one needs to do to install apart from adding the theme as a git submodule (and moving the example project folders)?
I added a few folders in content and the blogs there do not have the open/close feature that post has. It looks like I am missing something.
### Configuration

 - **Operating system with its version**: linux 20.04
 - **Browser with its version**: firefox 75.0 (64-bit)
 - **Hugo version**: v0.68.3
 - **Tranquilpeak version**: .4.7-BETA
 - **Do you reproduce on https://tranquilpeak.kakawait.com demo?**: yes perfectly

**Comment by ourmaninindia** [comment]
I discovered it was because sidebar in the example files are set somewhere (where I failed to see) to 5 and mine were reading the config.toml file where it was 2. If I set it to file I see the difference response.

Is one suppose to do something with the Gruntfile.js?

**Comment by kakawait** [comment]
There is nothing more than cloning project in theme folder (no need grunt or something else if you're not changing core component of theme itself)

But I'm not sure to understand your problem. Do you have some screenshots?
