### ISSUE TITLE
Deploying to github pages issue

### ISSUE THREAD

**Issue by jjasser** [kakawait/hugo-tranquilpeak-theme#422]
### Steps to deploy

 - Created two separate repositories. One for deploying the site **username.github.io**, and the other with all the folders once typing in hugo new site.

- Copied over the config.toml from exampleSite placed it into the top folder directory. I only changed my name to **jobin**, and set the base URL to **username.github.io**

- Added .gitignore for /public

- Ran a local version to test with "hugo serve" and everything looks fine

- Did a "hugo -d <username>.github.io and pushed everything to github, and now I see the following output below.

![image](https://user-images.githubusercontent.com/13125864/81224558-c28e5780-8f9c-11ea-9267-75aa9e53295b.png)

Not sure why it isn't showing up as my local version and would appreciate some guidance. Thank you!

**Comment by dacanizares** [comment]
Try to set baseURL = "https://username.github.io/"

It's working on my side: https://github.com/TheScienceOfCode/thescienceofcode.github.io

**Comment by george-kan** [comment]
@jjasser Did you find a solution to the issue perhaps? I have the same unfortunately

**Comment by dacanizares** [comment]
I've just set the baseURL accordingly to the github page and it worked: https://github.com/TheScienceOfCode/thescienceofcode.github.io/blob/dev/config.toml

**Comment by george-kan** [comment]
Yes that worked, thank you very much :)

**Comment by kakawait** [comment]
thank you @dacanizares for answered. I can close the issue now.
