### ISSUE TITLE
Enable math expressions (LaTeX)

### ISSUE THREAD

**Issue by franckess** [kakawait/hugo-tranquilpeak-theme#423]
### Configuration

 - **Operating system with its version**: 
 - **Browser with its version**: Chrome version 81.0.4044.138 (Official Build) (64-bit)
 - **Hugo version**: Hugo Static Site Generator v0.70.0/extended darwin/amd64
 - **Tranquilpeak version**: 0.4.7-BETA
 - **Do you reproduce on https://tranquilpeak.kakawait.com demo?**: **Yes**

### Actual behavior
Cannot generate Latex blocks when rendering `.md` file
Similar problem: [link](https://community.rstudio.com/t/enable-math-expressions-latex-on-blogdown-hugo-blog/18894)

<img width="817" alt="Screen Shot 2020-05-15 at 12 03 10 am" src="https://user-images.githubusercontent.com/7226560/81944185-bd39a880-963f-11ea-976b-470e68bef9c9.png">

### Expected behavior

<img width="851" alt="Screen Shot 2020-05-16 at 11 13 06 am" src="https://user-images.githubusercontent.com/7226560/82106753-4945f000-9766-11ea-961d-c7f1946d90ed.png">

**Disclaimer**: I am pretty new to Hugo and I would need detailed explanations to resolve this issue. Thanks :)

**Comment by franckess** [comment]
@yihui you proposed a solution to this problem here: [link](https://community.rstudio.com/t/enable-math-expressions-latex-on-blogdown-hugo-blog/18894/5)
How can we make that work for this theme?
Many thanks

**Comment by franckess** [comment]
Issue resolved as explained here: [https://divadnojnarg.github.io/blog/mathjax/](https://divadnojnarg.github.io/blog/mathjax/)
@kakawait do you want me to make a PR for this?

**Comment by kakawait** [comment]
PR are always welcome if you think that need it
