### ISSUE TITLE
Codeblock broken in Hugo v0.71.1

### ISSUE THREAD

**Issue by py-crash** [kakawait/hugo-tranquilpeak-theme#429]
### Configuration

 - **Operating system with its version**:  Manjaro 20.0.1
 - **Hugo version**:  v0.71.1
 - **Tranquilpeak version**: 0.4.7-BETA, 0.5.0-SNAPSHOT
 - **Do you reproduce on https://tranquilpeak.kakawait.com demo?**: Yes, also breaks when trying to build example site

### Actual behavior
When trying to build the site  using hugo v0.71.1 (obtained from the snap), it breaks throwing the following message:

```
Error: Error building site: "$PATH/exampleSite/content/posts/Tags-plugins-showcase.md:77:1": failed to render shortcode "codeblock": failed to process shortcode: $PATH/exampleSite/themes/hugo-tranquilpeak-theme/layouts/shortcodes/codeblock.html:23:15": execute of template failed: template: shortcodes/codeblock.html:23:15: executing "shortcodes/codeblock.html" at <($.Scratch.Get "c-url") ($.Scratch.Get "c-title")>: can't give argument to non-function $.Scratch.Get "c-url"
```
_Note:_ I replaced the actual path with `$PATH`

### Expected behavior
Hugo builds the site without problems, as it happens with hugo v0.70.0 (current version in the Manjaro repo)

### Steps to reproduce the behavior
Just run `hugo`.

**Comment by kakawait** [comment]
Could you please test new release `0.4.8-BETA`?

**Comment by py-crash** [comment]
It works! Thank you for fixing it so fast. :smile:
