### ISSUE TITLE
Update js libraries

### ISSUE THREAD

**Issue by FloMiau** [kakawait/hugo-tranquilpeak-theme#432]
Hey there,

the file "layouts/partials/script.html" includes several javascript libraries. The versions used are outdated. In case of jQuery there are multiple security flaws known.

Can you please update the libraries? I am using jQuery 3.5.0 for my blog and it works, but I can't test everything.

- jQuery:
  - in use: 2.2.4
  - current version: 3.5.1
- highlight.js:
  - in use: 9.12
  - current version: 10.0.3
- prism.js:
  - in use: 1.8.3
  - current version: 1.20.0
- jquery.fancybox.min.js:
  - in use: 2.1.7
  - current version: 3.5.7
- Mathjax:
  - in use: 2.7.4
  - current version 3.0.5
- moment.js
  - in use: 2.19.1
  - current version 2.26.1
- algoliasearch
  - in use: 3.24.5
  - current version: 4.2.0

**Comment by rugk** [comment]
If you wanna test https://github.com/kakawait/hugo-tranquilpeak-theme/pull/435, there is a PR. 😃

**Comment by kakawait** [comment]
is planned for next release thank

**Comment by kakawait** [comment]
thx everything updated except Mathjax and algolia's stuffs
