### ISSUE TITLE
Normal Codeblock Highlighting Broken with latest hugo

### ISSUE THREAD

**Issue by xiaoyunyang** [kakawait/hugo-tranquilpeak-theme#434]
### Configuration

 - **Operating system with its version**:  MacOS 10.15.2
 - **Browser with its version**: Chrom, Version 81.0.4044.138
 - **Hugo version**: v0.71.0
 - **Tranquilpeak version**: 0.4.8-BETA
 - **Do you reproduce on https://tranquilpeak.kakawait.com demo?**: Yes
 

### Actual behavior

The normal codeblock syntax highlighting is unreadable. 

<img width="258" alt="Screenshot 2020-05-30 19 11 40" src="https://user-images.githubusercontent.com/5825343/83340709-696ac880-a2a9-11ea-8c56-9f7f4c309025.png">

For example, the image above shows the codeblock generated for the following javascript codeblock in the markdown:

<img width="211" alt="Screenshot 2020-05-30 19 20 19" src="https://user-images.githubusercontent.com/5825343/83340814-a4213080-a2aa-11ea-9d1c-df6ac053d02b.png">

The highlighting in codeblock shortcode still seems to be correct.
<img width="303" alt="Screenshot 2020-05-30 19 21 44" src="https://user-images.githubusercontent.com/5825343/83340832-d0d54800-a2aa-11ea-9d44-bf80a989061e.png">

### Expected behavior

The normal codeblock's highlighting should look identical to the codeblock shortcode's highlighting. The style of the highlighted block is probably being overwritten by another style. Reverting back to an older version of hugo (v0.56.3) seems to correct the highlighting issue.

### Steps to reproduce the behavior

Upgrade hugo to the latest version (v0.71.0).

**Comment by kakawait** [comment]
Since `0.60` hugo is shipped with syntax highlight that seems to be overriding Highlight.js

You could disable it by using

```toml
[markup]
  [markup.highlight]
    codeFences = false
``` 

inside your `config.toml`

**Comment by kakawait** [comment]
Until #486 best is used workaround.

I'll close in flavor of #486
