### ISSUE TITLE
How to change the background image of the sidebar?

### ISSUE THREAD

**Issue by r3econ** [kakawait/hugo-tranquilpeak-theme#437]
I looked in the docs and can't find it. Where can I customize the background of the side bar?

<img width="566" alt="without_hierarchical_categories" src="https://user-images.githubusercontent.com/505054/84602375-328ada00-ae87-11ea-8496-4e865dfb5ce9.png">

Thanks!

**Comment by TechGeek01** [comment]
Drop an image into the **static** directory. In my case, I named mine side-banner.jpg. Then, in config.toml, change **coverImage** under **[params]** to reference the file, relative to static. That is, for mine, under **static/img/side-banner.jpg**, I have **/img/side-banner.jpg** as the value for **coverImage**.

**Comment by kakawait** [comment]
> Drop an image into the **static** directory. In my case, I named mine side-banner.jpg. Then, in config.toml, change **coverImage** under **[params]** to reference the file, relative to static. That is, for mine, under **static/img/side-banner.jpg**, I have **/img/side-banner.jpg** as the value for **coverImage**.

can't say more is perfect

**Comment by kakawait** [comment]
@TechGeek01 has respond
