### ISSUE TITLE
Hardcoded main section name in `where` clauses

### ISSUE THREAD

**Issue by 414n** [kakawait/hugo-tranquilpeak-theme#444]
### Configuration

 - **Operating system with its version**: Linux Slackware64 14.2
 - **Browser with its version**: Mozilla Firefox 68 ESR
 - **Hugo version**: 0.60.1
 - **Tranquilpeak version**: 0.4.8-BETA
 - **Do you reproduce on https://tranquilpeak.kakawait.com demo?**: built-time issue, can't reproduce
 

### Actual behavior

If the site uses more than a main section type (e.g. something other than `post` or `posts`), only content under the main section type is presented in list/summary pages, the categories page etc.

### Expected behavior

The theme should refrain from using the hardcoded `post`/`post` type when looping over pages to compile a list and use the `mainSections` site parameter as suggested in [the docs](https://gohugo.io/functions/where/#mainsections).

Relevant upstream Hugo issue: gohugoio/hugo#3206

### Steps to reproduce the behavior

 1. create a test site with a number of posts under the `post` section
 2. move them all to a new section `test`, e.g. `mv content/post content/test`
 3. no posts are present in the home page list or under the archive or categories pages.

I have already changed some templates to implement this feature. Will publish a PR soon.

**Comment by kakawait** [comment]
planned for next release
