### ISSUE TITLE
twitter is not using coverImage even though it is present

### ISSUE THREAD

**Issue by matcha440** [kakawait/hugo-tranquilpeak-theme#448]
### Configuration

 - **Operating system with its version**: Windows 10
 - **Browser with its version**: Firefox 79.0
 - **Hugo version**: 0.74.3
 - **Tranquilpeak version**: 0.4.8-BETA
 - **Do you reproduce on https://tranquilpeak.kakawait.com demo?**: Did not try
 

### Actual behavior
`Author.picture` is used when linking a post to a tweet.  The post does have a cover image, but it doesn't show in the tweet.

I suspect the problem to be the order of meta tags, and I think Twitter will use the last one it sees if there are multiple with the same name.  If you look at how this is done in the original hexo version, the tags show coverImage last on the list
https://github.com/LouisBarranqueiro/hexo-theme-tranquilpeak/blob/master/layout/_partial/head.ejs#L172

However, in the hugo version the gravatar image / author image is last on the list so therefore Twitter will give that the highest precedence.
https://github.com/kakawait/hugo-tranquilpeak-theme/blob/e1d2c5d5cb1efb687ed698782f99df576e7db084/layouts/partials/meta.html#L76

### Expected behavior
If the post has a coverImage, using a link to a post on a tweet should show that coverImage instead of favicon.  Having the meta tags in the correct order should clear this up.

### Steps to reproduce the behavior
Using a post that has a cover image, post a link to that post on Twitter.

**Comment by matcha440** [comment]
I tried a workaround by overriding the meta.html file to change the order of the meta tags, but it didn't seem to change the behavior at all.

**Comment by ruevko** [comment]
@matcha440 changing the meta order did work for me, but I updated the theme rather than override the layout #450
