### ISSUE TITLE
can't change avatar

### ISSUE THREAD

**Issue by JanU-YieG** [kakawait/hugo-tranquilpeak-theme#460]
my config is:
```
[author]
  name = "Borer"
  bio = "**Keep Simple, Keep Stupid !**"
  job = "Philosophy|engineer"
  location = "China"
  # Your Gravatar email. Overwrite `author.picture` everywhere in the blog
  gravatarEmail = "januyieg@aliyun.com"
  # Your profile picture
  # Overwritten by your gravatar image if `author.gravatarEmail` is filled
  picture = "https://janu-yieg.github.io/author.jpg"
  avatar = "https://janu-yieg.github.io/author.jpg"
  # Your Twitter username without the @. E.g : thibaudlepretre
  # twitter = "thibaudlepretre"
  # Your google plus profile id. E.g : +ThibaudLepretre or 114625208755123718311
  # googlePlus = "+ThibaudLepretre"

```
then my avatar is default one which i don't know where find.

**Comment by JanU-YieG** [comment]
please help me!

**Comment by JanU-YieG** [comment]
i change the source code:
**layouts->partials->header.html:**
        <img class="header-picture" src="{{ $.Site.Author.avatar }}{{ if in . "//www.gravatar.com/avatar/" }}?s=90{{ end }}" alt="{{ i18n "global.author_picture" }}" />
**layouts->partials->sidebar.html:**
<img class="sidebar-profile-picture" src="{{ $.Site.Author.avatar }}{{ if in . "//www.gravatar.com/avatar/" }}?s=110{{ end }}"|▸    archetypes/
       alt="{{ i18n "global.author_picture" }}" />

**Comment by jehoshua7** [comment]
You only need to change two lines in `config.toml`

1.  Change the author.picture

`picture = "https://example.com/images/profile.webp"`

2.  Comment out this line (author.gravatarEmail)

`#gravatarEmail = "thibaud.lepretre@gmail.com"`

The comment in `config.toml` needs to be changed, **from**

`# Overwritten by your gravatar image if `author.gravatarEmail` is filled`

**to**

`# Overwritten by your gravatar image if `author.gravatarEmail` is commented`
