### ISSUE TITLE
Can the home page be one of the posts in content/post?

### ISSUE THREAD

**Issue by olamarre** [kakawait/hugo-tranquilpeak-theme#469]
Hi! Really like this theme :smile: 

Is there any way to set the home page as one of the posts in `content/post` (instead of the default list of blog summaries)? If so, how can this be achieved? I couldn't find any setting about this in `config.toml`. Thanks

### Configuration

 - **Operating system with its version**: Linux Ubuntu 20.04
 - **Browser with its version**: Google Chrome Version 90.0.4430.93 (Official Build) (64-bit)
 - **Hugo version**: Hugo Static Site Generator v0.80.0-792EF0F4 linux/amd64 BuildDate: 2020-12-31T13:37:58Z
 - **Tranquilpeak version**: 0.4.8-BETA

**Comment by fu-sen** [comment]
The theme does not take this into account. Therefore, it is necessary to edit the template.
**This requires some experience with Hugo.** You probably want it from `https://example.net/`:

1. Copy [/themes/hugo-tranquilpeak-theme/layouts/_default/single.html](https://github.com/kakawait/hugo-tranquilpeak-theme/blob/master/layouts/_default/single.html) to **/layouts/index.html**
2. Generate **/content/_index.md**
3. Refer to `hugo server` and adjust 2 files

Although it is not directly related...

> * **Hugo version**: Hugo Static Site Generator v0.80.0-792EF0F4 linux/amd64 BuildDate: 2020-12-31T13:37:58Z

Currently Hugo version is [Hugo v0.84.0](https://github.com/gohugoio/hugo/releases). Also consider updating Hugo.

**Comment by olamarre** [comment]
Sounds good, thanks for the help!
