### ISSUE TITLE
Retain option to use Hugo default code syntax highlighting in future versions

### ISSUE THREAD

**Issue by katiepress** [kakawait/hugo-tranquilpeak-theme#474]
I just started using your theme and could not get the custom hljs to work no matter what I did. Then is searched on here and noticed a reply to one of the comments that Hugo's newest version has default highlighting that is overriding the tranquilpeak hljs, so I thought I would see if I could change the syntax highlighting using the Hugo default instead. The Hugo/Chroma default is Monokai theme which is as some others pointed out, quite hard to read (especially in light version??!)

I followed this structure https://gohugo.io/getting-started/configuration-markup#highlight
<img width="611" alt="Screen Shot 2021-08-08 at 7 05 04 PM" src="https://user-images.githubusercontent.com/44142983/128649712-f27729a5-c16c-461b-8ddd-06babaf25fe9.png">

And I used this Chroma Playground website to choose the theme https://swapoff.org/chroma/playground/

My end result looks like this in the config.yaml file (for some reason R blogdown makes it a yaml instead of toml but the overall idea is the same)

<img width="467" alt="Screen Shot 2021-08-08 at 6 47 52 PM" src="https://user-images.githubusercontent.com/44142983/128649251-8fa07116-e762-4f26-a5ba-a0ffde4d73a8.png">

The only other thing I had to do was change the background and color in a couple places in the scss file that lives in 
themes/Hugo-tranquilpeak-theme/static/css like so (colors are from the base16-snazzy theme):
<img width="554" alt="Screen Shot 2021-08-08 at 6 52 01 PM" src="https://user-images.githubusercontent.com/44142983/128649411-09589f82-6642-46a3-bf31-792ec02433ac.png">

The final result of the styling is this: 
<img width="746" alt="Screen Shot 2021-08-08 at 6 55 48 PM" src="https://user-images.githubusercontent.com/44142983/128649494-daa4e91f-d77b-42eb-acfa-a901e728615a.png">

All that to say, I would appreciate it if in future versions you could continue to use the Hugo default syntax highlighting, perhaps when the syntaxHighlighter: highlight.js is commented out or not used? This is such an easy way to change the styling, especially for those of us who are using the theme through R and blogdown (I'm not really sure how to use these build tools or what Grunt is??). 

I really do like this theme, thank you for putting it together! 

### Configuration

 - **Operating system with its version**:  MacOS (m1) Big Sur
 - **Browser with its version**: Safari
 - **Hugo version**: 0.87.0 extended
 - **Tranquilpeak version**:  0.4.8 beta
 - **Do you reproduce on https://tranquilpeak.kakawait.com demo?**: no
 

### Steps to reproduce the behavior

**Comment by kakawait** [comment]
Yes this theme is not supporting the built-in Hugo syntax highlighter.
I've created a dedicated issue for that #486 

I'll close as duplicate
