### ISSUE TITLE
Google analytics dont work 

### ISSUE THREAD

**Issue by stiliajohny** [kakawait/hugo-tranquilpeak-theme#497]
Google analytics dont work 

https://github.com/kakawait/hugo-tranquilpeak-theme/blob/0990bf9d188edfb7feb86a5974225a344242d359/layouts/partials/head.html#L61-L65

see the output code here https://github.com/stiliajohny/stiliajohny.github.io/blob/c995fec3f87dd9816bfd228cbc53fcd303d143e6/index.html#L85-L96

Suggested Google snippet is:

```html

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-177229457-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-177229457-1');
</script>
```

My config is here: 
https://github.com/stiliajohny/stiliajohny.github.io/blob/1a6dd048fdb4cba2810d28975cc9b965e261f668/config.toml#L7

My page is here 
https://stiliajohny.github.io/

**Comment by kakawait** [comment]
As you know most of part is on `head.html` but after `_internal/google_analytics.html` is Hugo's internal template that is part of Hugo and not the theme.

https://gohugo.io/templates/internal/#google-analytics

And code is here

https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/templates/google_analytics.html

To be honest, GA on https://tranquilpeak.kakawait.com/ works and by checking your `config.toml` I didn't see something wrong. But not yet time to test directly your file.

**Comment by kakawait** [comment]
And even with your `config.toml`

<img width="1427" alt="Screen Shot 2021-09-02 at 12 37 11" src="https://user-images.githubusercontent.com/275609/131829416-913ec167-f98e-479b-b29d-9e0a00985d4c.png">

GoogleAnalytics seems to be load

**Comment by kakawait** [comment]
And inside your blog I see it (maybe you've did update?)

<img width="803" alt="Screen Shot 2021-09-02 at 12 38 36" src="https://user-images.githubusercontent.com/275609/131829567-dbe246a6-52ff-4f4e-8156-91447326fe4c.png">

**Comment by stiliajohny** [comment]
aw, Thanks for checking in depth. 
let me check my google side, I might be doing something wrong there.

**Comment by kakawait** [comment]
Do you find root cause? Is issue still needed?

**Comment by stiliajohny** [comment]
we can close it for now, I believe it is to do with my google analytics
