### ISSUE TITLE
shared link shows my profile picture

### ISSUE THREAD

**Issue by stiliajohny** [kakawait/hugo-tranquilpeak-theme#499]
### Configuration

 - **Operating system with its version**: 
 - **Browser with its version**: Firefox 91.0
 - **Hugo version**: 0.87.0_extended
 - **Tranquilpeak version**: 0.51.0
 - **Do you reproduce on https://tranquilpeak.kakawait.com demo?**:
 

### Actual behavior

When sharing a link of a blog in LinkedIn and any other social media it resolved with a thumbnail of the profile picture like this https://github.com/kakawait/hugo-tranquilpeak-theme/blob/0990bf9d188edfb7feb86a5974225a344242d359/exampleSite/config.toml#L55 

### Expected behavior

the URL thumbnail should be an image of the URL 

### Steps to reproduce the behavior

Use a link of a post and share it on LinkedIn

**Comment by stiliajohny** [comment]
![image](https://user-images.githubusercontent.com/17669235/131911578-d2e4166a-49f5-43ad-8d47-320f62f095a9.png)

![image](https://user-images.githubusercontent.com/17669235/131911624-9eac4700-5d0d-44c9-a88e-e90e72dbe2d1.png)


the link I try to share is https://stiliajohny.github.io/2021/08/ssh-made-easy/

**Comment by stiliajohny** [comment]
when I try to share one of your links 
![image](https://user-images.githubusercontent.com/17669235/131911920-6dbec259-ca2d-4c88-8433-06a1029e9420.png)

**Comment by kakawait** [comment]
But what you're expecting? Using post thumbnail image?

**Comment by stiliajohny** [comment]
correct... when sharing your link it takes the post thumbnail ...

**Comment by kakawait** [comment]
Seems to be related to #450

**Comment by stiliajohny** [comment]
agree.. 
Closing as related to #450
