### ISSUE TITLE
fix gitalk redirect 404 and Validation Failed(422)

### ISSUE THREAD

**Issue by duval1024** [kakawait/hugo-tranquilpeak-theme#504]
I found two problems.

First，there is an error in _comment.html_  : 

```
 new Gitalk({
          clientID: '{{ .Site.Params.comment.gitalk.client_id }}',
          clientSecret: '{{ .Site.Params.comment.gitalk.client_secret }}',
          repo: '{{ .Site.Params.comment.gitalk.repo }}',
          owner: '{{ .Site.Params.comment.gitalk.owner }}',
          admin: ['{{ .Site.Params.comment.gitalk.owner }}'],
          id: '{{ .RelPermalink }}',
          ...{{ .Site.Params.comment.gitalk.options | jsonify | safeJS }}
        }).render('gitalk')
```
_gitalk.client_id_ should be _gitalk.clientId_
_client_secret_ should be _clientSecret_

Second... ( to be continue）

Please let me fix it...

**Comment by kakawait** [comment]
@duval1024 if you've second issue can you please open on different issue?

I'll fix the typo on variable name for next drop

**Comment by kakawait** [comment]
@duval1024 fixed on `develop` branch if you want to test.

**Comment by kakawait** [comment]
Arf I didn't see

> Please let me fix it...

I can let you fix second issue?

**Comment by duval1024** [comment]
> Arf I didn't see, sorry 🙏
> 
> > Please let me fix it...
> 
> I can let you fix second issue?

hah，it is ok. I am learning how to make a pull request. I will try to open a different issue for the second problem

**Comment by kakawait** [comment]
> > Arf I didn't see, sorry 🙏
> > > Please let me fix it...
> > 
> > 
> > I can let you fix second issue?
> 
> hah，it is ok. I am learning how to make a pull request. I will try to open a different issue for the second problem

Sure and I'll let you learn.
If need help tell me.
