### ISSUE TITLE
Validation Failed(422) found in gitalk

### ISSUE THREAD

**Issue by duval1024** [kakawait/hugo-tranquilpeak-theme#507]
Here comes the second issues. Please let me fix it if needed this time.

### Actual behavior
 I use gitalk in Chinese language.  And the URI encoding makes the parameter named _id_  pretty long（more than 50 chars）which results in Validation Failed （422）

```
new Gitalk({
          clientID: '{{ .Site.Params.comment.gitalk.clientId }}',
          clientSecret: '{{ .Site.Params.comment.gitalk.clientSecret }}',
          repo: '{{ .Site.Params.comment.gitalk.repo }}',
          owner: '{{ .Site.Params.comment.gitalk.owner }}',
          admin: ['{{ .Site.Params.comment.gitalk.owner }}'],
          id: '{{ .RelPermalink }}',  // Ensure uniqueness and length less than 50
          ...{{ .Site.Params.comment.gitalk.options | jsonify | safeJS }}
        }).render('gitalk')
```
### How to fix

wrapper  _{{ .RelPermalink }}_ by decodeURI function.

e.g. 
![image](https://user-images.githubusercontent.com/21072525/132120771-0704d2d6-13fb-4fa7-a329-6ceee0161130.png)

![image](https://user-images.githubusercontent.com/21072525/132120793-94372ca6-70de-41fc-a091-72283a62656d.png)

**Comment by kakawait** [comment]
I've assigned you the issue. I'll let you create a Pull Request
