### ISSUE TITLE
Add my blog into the showcase

### ISSUE THREAD

**Issue by InderdeepBajwa** [kakawait/hugo-tranquilpeak-theme#51]
Hey, add my blog into the showcase:
https://www.DesktopLuxury.com
Author - Inderdeep Singh Bajwa

**Comment by kakawait** [comment]
@InderdeepBajwa Thank you for using this theme.

Can I take a screenshot of the actual site or you want to wait to add some more content before creating the static screenshot for showcase?

**Comment by InderdeepBajwa** [comment]
That would really be great. However, I'll be uploading thumbnail images on the website which would deliberately look terrific, making the showcase better. If you suggest to add images as soon as possible, I'll upload them and email you once every thing is finished.

**Comment by kakawait** [comment]
Ok I will screenshot and update showcase asap

**Comment by kakawait** [comment]
Added on https://github.com/kakawait/hugo-tranquilpeak-theme/wiki/Showcase
