### ISSUE TITLE
CoverImage Can't be shown

### ISSUE THREAD

**Issue by umnooob** [kakawait/hugo-tranquilpeak-theme#525]
I don't know if it's a bug or mistake I made,hope someone could help me

### Configuration

 - **Operating system with its version**: win10
 - **Browser with its version**:Microsoft Edge 94.0.992.31
 - **Hugo version**: hugo v0.88.1
 - **Tranquilpeak version**: 0.5.2-BETA 
 - **Do you reproduce on https://tranquilpeak.kakawait.com demo?**:No
 

### Actual behavior
can't see cover image
![image](https://user-images.githubusercontent.com/41941089/134836237-24bd8d57-e99b-4120-a6e5-df26194c1beb.png)

### Expected behavior
it should show cover image

### Steps to reproduce the behavior
in config.toml ,I set coverImage = "https://tranquilpeak.kakawait.com/images/cover.jpg" for test and start hugo server.
However,when I Review element in Edge ,I found  no cover included,shown as below:
![image](https://user-images.githubusercontent.com/41941089/134836148-dce043ba-8632-4629-a925-c77daf86d904.png)
While normally it should be :
![image](https://user-images.githubusercontent.com/41941089/134836340-a2135876-3214-46c1-a2c0-3e93c97fdec6.png)

**Comment by kakawait** [comment]
Do you have sample repo to reproduce?

**Comment by umnooob** [comment]
> Do you have sample repo to reproduce?

emm... cause my githubPage is occupied,I uploaded 2 repo for reproducing:
changes made in theme: https://github.com/umnooob/hugo-tranquilpeak-theme
generated web: https://github.com/umnooob/reproduce-repo
thanks for your kindness.

**Comment by umnooob** [comment]
I try to rename config.toml and name it again.
Then it shows cover image magically,but I still don't know what's wrong with it.

Thanks anyway.

**Comment by kakawait** [comment]
Good to know. Sorry for delay I mainly work on projet on weekend only and I was on vacation
