### ISSUE TITLE
Click on author profile pic not shows About Card.

### ISSUE THREAD

**Issue by ramkumarrammohan** [kakawait/hugo-tranquilpeak-theme#529]
### Configuration

 - **Operating system with its version**: 
 - Windows 10
 - **Browser with its version**:
 - Google Chrome - 94.0.4606.81
 - **Hugo version**: 
 - hugo v0.88.1-5BC54738 windows/amd64 BuildDate=2021-09-04T09:39:19Z VendorInfo=gohugoio
 - **Tranquilpeak version**: 
 - latest release - 0.5.3-BETA
 - **Do you reproduce on https://tranquilpeak.kakawait.com demo?**:
 - no. But try loading ramkumarrammohan.github.io/blog
 

### Actual behaviour
Click on Author pic or About link from sidebar not showing the about card. Only URL changes with /#about.
Ref: https://ramkumarrammohan.github.io/blog/#about

### Expected behavior
Click on the Author pic or About link should show the About Card in the centre of the screen with the background cover image.

### Steps to reproduce the behaviour
1. Go to site ramkumarrammohan.github.io/blog.
2. Click on the author pic or About from the sidebar.

**Comment by kakawait** [comment]
Is the source of your blog available somewhere?
