### ISSUE TITLE
comments: false does not work

### ISSUE THREAD

**Issue by chbloca** [kakawait/hugo-tranquilpeak-theme#539]
### Configuration

 - **Operating system with its version**: 
 - **Browser with its version**:
 - **Hugo version**: 
 - **Tranquilpeak version**: 
 - **Do you reproduce on https://tranquilpeak.kakawait.com demo?**:
 

### Actual behavior
Once disqus is enabled in the config file
```
 [params.comment]
    [params.comment.disqus]
      enable = false
```
the disqus section appears globally in every page, even in those which it should not despite having declared ```comments: false``` in the front matter.

### Expected behavior
The disqus appears globally in every page except for the ones in whose front matter is declared ```comments: false```.

### Steps to reproduce the behavior

**Comment by mathaou** [comment]
Replace line 2 in layouts/partials/post/comments.html with this:

```html
{{ if and ($.Params.comments) (.Site.Params.comment.disqus.enable) (not (.Site.Config.Privacy.Disqus.Disable)) }}
```

Then you can manipulate comments on a post-by-post basis.

**Comment by christenbc** [comment]
Thanks for your reply
