### ISSUE TITLE
Migrate to built in hugo SEO template

### ISSUE THREAD

**Issue by kakawait** [kakawait/hugo-tranquilpeak-theme#54]
https://github.com/spf13/hugo/blob/142558719324aa1628541d556ef1fa2d123f1e68/tpl/tplimpl/template_embedded.go#L159

**Comment by jhabdas** [comment]
Example implementation of OpenGraph using the internal template plus a fix for a bug I found in it: https://github.com/comfusion/after-dark/blob/002ff76d431a6b7dfdaa7b7f03e123c26842f80d/layouts/_default/baseof.html#L17-L18

Here's what the cards look like, once implemented: https://github.com/comfusion/after-dark#open-graph
