### ISSUE TITLE
Tranquilpeak is not able to render twitter's shortcode

### ISSUE THREAD

**Issue by pnijhara** [kakawait/hugo-tranquilpeak-theme#540]
### Configuration

 - **Operating system with its version**: MacOS Catalina 10.15.7
 - **Browser with its version**: Brave Browser Version 1.31.91 Chromium: 95.0.4638.69 (Official Build) (x86_64)
 - **Hugo version**: 0.74.3
 - **Tranquilpeak version**:  latest
 
 

### Actual behavior
On writing `{{< tweet user="SanDiegoZoo" id="1453110110599868418" >}}` in a post, it is throwing the following error:
```bash
failed to render shortcode "tweet": failed to process shortcode: template: _internal/shortcodes/tweet.html:6:82: executing "_internal/shortcodes/tweet.html" at <index .Params 0>: error calling index: value has type int; should be string
```

### Expected behavior
It should render the tweet.

### Steps to reproduce the behaviour
Create a new post and copy the above tweet's shortcode.

**Comment by kakawait** [comment]
Hum that strange, `tweet` shortcode is not managed by theme but directly by Hugo.

Did you have time to try with other (whatever) theme? to see if related to theme?

**Comment by pnijhara** [comment]
Sure, I'll try with some other theme and get back to you soon.

**Comment by pnijhara** [comment]
@kakawait I tested twitter's short code on other themes and looks like the problem was the hugo version. I upgraded hugo and everything is working fine.
Thanks!
