### ISSUE TITLE
tabbed-codeblock is not working on the exampleSite

### ISSUE THREAD

**Issue by xanne3d** [kakawait/hugo-tranquilpeak-theme#572]
I am experimenting with the default exampleSite code with no modification. 

My Hugo version is: `hugo v0.101.0-466fa43c16709b4483689930a4f9ac8add5c9f66+extended windows/amd64 BuildDate=2022-06-16T07:09:16Z VendorInfo=gohugoio`

My Chrome browser is: `Version 104.0.5112.101 (Official Build) (64-bit)`

When I render the exampleSite (as is, no modification) it does not render `tabbed-code-block` like how it is displayed here:

Expected behavior:
https://tranquilpeak.kakawait.com/2014/10/tags-plugins-showcase/#tabbed-code-block

Actual behavior:

![image](https://user-images.githubusercontent.com/109448282/185770661-2b64e8ad-b22e-42c9-be54-312f65eb525e.png)

Everything is default out of the box in my environment. Why everything works fine except tabbed-codeblock ?

**Comment by jehoshua7** [comment]
Are these any help ?

https://github.com/kakawait/hugo-tranquilpeak-theme/issues?q=is%3Aissue+tabbed+is%3Aclosed

https://github.com/kakawait/hugo-tranquilpeak-theme/issues?q=is%3Aissue+tabbed+is%3Aopen

**Comment by kakawait** [comment]
I'm not able to reproduce with latest hugo version `hugo v0.101.0+extended darwin/arm64 BuildDate=unknown`

Do you think you can do a zip of your setup?
