### ISSUE TITLE
Update FontAwesome

### ISSUE THREAD

**Issue by Armagetron** [kakawait/hugo-tranquilpeak-theme#58]
This is partially a question and partially a request. How can I update the FontAwesome version? I wanted to use an icon that is not present in the version included.
It would of course be nice if the most up-to-date version is automatically included.

**Comment by kakawait** [comment]
Yes no problem to update it. I have to check how can I always use latest version.

**Comment by kakawait** [comment]
I'm also thinking about directly using external dep like FontAwesome or Jquery from official CDN instead of bundling it

**Comment by Armagetron** [comment]
I had them problem, that you combined the FontAwesome css with some other code. Maybe you could split that. A CDN solution might also work but I would like to have that as an option if it's possible.

**Comment by kakawait** [comment]
At start it was for performance impact in order to reduce number of request. 

For `0.2.0-ALPHA` I will upgrade FontAwesome to latest version for sure. About refactoring/rethinking external deps and bundl-isation I want to take more time to think about every possibility.
