### ISSUE TITLE
Error checking out submodules?

### ISSUE THREAD

**Issue by db369** [kakawait/hugo-tranquilpeak-theme#583]
### Configuration

 - **Operating system with its version**: 
 -- Linux Mint 21.1 Cinnamon

 - **Browser with its version**:
 -- Vivaldi Linux Mint 21.1 Cinnamon5.6.2867.62 (Stable channel) stable (64-bit)

 - **Hugo version**: 
 -- 0.110.0

 - **Tranquilpeak version**: 
 --0.5.3-BETA

 - **Do you reproduce on https://tranquilpeak.kakawait.com demo?**:
 -- no

### Actual behavior

Using R (Posit) and blogdown to build site. Github and netlify to host. Pushing to netlify results in the following error:

Error checking out submodules: : fatal: No url found for submodule path 'themes/hugo-tranquilpeak-theme' in .gitmodules
: exit status 128

I tried removing the entire theme and re-installing, but same results.

### Expected behavior
Web site runs nicely locally

### Steps to reproduce the behavior

**Comment by db369** [comment]
It seems I fixed this by adding the url to your git to my .gitmodules file and resyncing.

**Comment by db369** [comment]
(Trying to close issue)

**Comment by No-drink** [comment]
I think the reason is because there is a .git folder in the theme folder, this will cause the git cannot recognize the files in the theme folder. Just delete it can fix it.
