### ISSUE TITLE
event widget or site 

### ISSUE THREAD

**Issue by Martin1001** [kakawait/hugo-tranquilpeak-theme#61]
- show events on a separate site or as a sidebar widget
- datasource should be an caldav server

**Comment by kakawait** [comment]
Could you explain me a bit more what you want to do? The calendar will be a `shortcode`?

**Comment by Martin1001** [comment]
Providing a special site or an sidebar widget that display current and upcoming events in a list or calendar view. This will help people to choose an event that suits to them.

**Comment by kakawait** [comment]
Ok but it may a bit out of scope of what theme should handle. Why not simply create an static page that handle such thing?

**Comment by Martin1001** [comment]
I think it could be an optional feature like disqus or google analytics

**Comment by kakawait** [comment]
Ok but where do you want to display such calendar?

Moreover I don't think the theme will manage it own calendar implementation, is more about linking a calendar service like *Google Calendar* or other, like `disqus` which is come with it's own frontend.

**Comment by Martin1001** [comment]
I agree we will provide an add-on that will provide a calendar implementation. You could close this issue.

**Comment by kakawait** [comment]
@Martin1001 I will try to focus on core theme feature until first non beta release then after we can see together to add some service like calendar. 

Even more I'm a bit busy this month I have to find free time to release asap 0.2.0-ALPHA
