### ISSUE TITLE
Page opens at the end of the page with Firefox

### ISSUE THREAD

**Issue by Martin1001** [kakawait/hugo-tranquilpeak-theme#69]
When I open the blog with Firefox, the page is not opened at the top.

**Comment by kakawait** [comment]
could you provide me more information about your système?

- OS with version
- FF with version

and do you reproduce the bug on https://tranquilpeak.kakawait.com ?

**Comment by kakawait** [comment]
@Martin1001 Moreover I'm asking myself if I did not forget to report the fix from

**Comment by Martin1001** [comment]
OSX 10.11 & Firefox OSR 38.3.0

**Comment by kakawait** [comment]
thank you for the feedback I will check it asap

**Comment by kakawait** [comment]
@Martin1001 As I tough I forget to report bug. That will be easy to fix
