### ISSUE TITLE
sidebar showing posts

### ISSUE THREAD

**Issue by jeremywho** [kakawait/hugo-tranquilpeak-theme#70]
My sidebar menu is showing my posts (I currently only have 2), any idea what is going on here? I'd just like to show the menu items with no posts. I have the default sidebar menu configuration.

![sidebar](https://cloud.githubusercontent.com/assets/331223/20728564/25927b14-b633-11e6-9973-bb852c24afe8.png)

**Comment by kakawait** [comment]
Which version are you using? Bug is on mobile, desktop and any browser?

I never saw that bug I need some more information sorry.

**Comment by jeremywho** [comment]
That shows up in Chrome on the desktop.  I haven't tried it on any other browser/platform.  I'm not sure the version, I cloned it a couple weeks ago and have been using grunt to build after making style changes.  I don't know what style changes would cause the posts to the show up like that.

**Comment by jeremywho** [comment]
This was my fault, in my posts I had:

    menu = "main"

Sorry!

**Comment by kakawait** [comment]
no prob if you find solution it's perfect!
