### ISSUE TITLE
'tags' link does not work

### ISSUE THREAD

**Issue by kongakong** [kakawait/hugo-tranquilpeak-theme#86]
Navigate to http://localhost:1313/tags/ and I see

    --- layout: page title: Tag Cloud footer: false ---
    {% tag_cloud %}

Do I need to install anything to enable to enable `tag_cloud`?

**Comment by kakawait** [comment]
Sorry @kongakong I don't know what are you talking about, there is no reference `tag_cloud` on the theme. Do you have more informations, like screenshot or sample to reproduce?

**Comment by kakawait** [comment]
Close due to inactivity, please feel free to re-open if relevant
